var artistClasses = {
  "0": "Abdel Halim Hafez",
  "1": "Asmahan",
  "2": "Azar Habib",
  "3": "Aziza Jalal",
  "4": "Baligh Hamdi",
  "5": "Fahd Ballan",
  "6": "Farid Al-Atrash",
  "7": "Fayrouz",
  "8": "Fayza Ahmed",
  "9": "Hanan",
  "10": "Karem Mahmoud",
  "11": "Layla Nazmi",
  "12": "Leila Mourad",
  "13": "Mohamad Abdel Mutallab",
  "14": "Mohamad Fawzi",
  "15": "Mohamad Jamal",
  "16": "Mohamad Khairy",
  "17": "Mohamed Abdel Wahab",
  "18": "Nagah Sallam",
  "19": "Nagib Alsarraj",
  "20": "Najat",
  "21": "Nasri Shamseddine",
  "22": "Nazek",
  "23": "Nazem Al Ghazali",
  "24": "Sabah",
  "25": "Sabah Fakhri",
  "26": "Saleh Abdel Hai",
  "27": "Salwa Al Katrib",
  "28": "Samir Yazbek",
  "29": "Samira Tawfik",
  "30": "Sayed Darwiche",
  "31": "Sayed Makkawi",
  "32": "Shadia",
  "33": "Sharifa Fadel",
  "34": "Souad Mohamad",
  "35": "Tony Hanna",
  "36": "Um Kalthum",
  "37": "Wadih Al Safi",
  "38": "Warda",
  "39": "Yasmin Al Khayam",
  "40": "Zaki Nassif"
};

var songClasses = {
  "0": "- Mohamed Abd El Wahab أنده علي الأحرار - محمد عبد الوهاب",
  "1": "- Mohamed Abd El Wahab نشيدالحرية(وطنيات3) - محمد عبد الوهاب",
  "2": "- Mohamed Abd El Wahab ياجمال النوروالحرية - محمد عبد الوهاب",
  "3": "- Mohamed Abd El Wahab يامصرزيك مالقيت مثالك - محمد عبد الوهاب",
  "4": "01 Wadih Al Safi - Dakalek Aal Rababa  وديع الصافي - دقلق عالربابة",
  "5": "02 Wadih Al Safi - Chayef Seher  وديع الصافي - شايف سحر",
  "6": "03 Wadih Safi - Tzakart  وديع الصافي - تذكرت",
  "7": "04 Wadih Al Safi - Bfaker Fik  وديع الصافي - بفكر فيك",
  "8": "05 Wadih Al Safi - Chou Byehla Kalami  وديع الصافي - شو بيحلا كلامي",
  "9": "06 Wadih Al Safi - Asfour Sawtak  وديع الصافي - عصفور صوتك",
  "10": "07 Wadih Al Safi - Rab el Jamal  وديع الصافي - رب الجمال",
  "11": "08 Wadih Al Safi - Rajea Men Jdid  وديع الصافي - راجع من جديد",
  "12": "AGLA ELAHEBA",
  "13": "AHLL ELMHABA",
  "14": "ALBAK TAMLY MHYARO",
  "15": "AMA BARAWA",
  "16": "ANA ALBY LEEK MAYAL",
  "17": "ANTA MESH ANDK HABIB",
  "18": "ATSHAN YA SABAYA",
  "19": "AYZAA AHRAB",
  "20": "Aa Droub El Mahboub",
  "21": "Aa Fajr Jdid",
  "22": "Aa Tlalina Aa Tlalina",
  "23": "Aad El Mohager Men Baad Gheiba",
  "24": "Aal Hawa",
  "25": "Aal Hob El Hob",
  "26": "Aala Dalouna",
  "27": "Aala Wastek Liffe Mandilek",
  "28": "Aali Aali",
  "29": "Aali Garra",
  "30": "Abdl Halmhafez Medly",
  "31": "Abo Oyoun Gareea - Abdel Halim Hafez أبوعيون جريئة - عبد الحليم حافظ",
  "32": "Aboul Mijana",
  "33": "Aboul Zilouf",
  "34": "Achki Limine",
  "35": "Addora",
  "36": "Adeste Fideles",
  "37": "Ady El Hayah - Fayza Ahmed أدى الحياه - فايزة أحمد",
  "38": "Agaby - Sayed Mekawy عجبي - سيد مكاوي",
  "39": "Agayeb Khesamak",
  "40": "Aghadan Alqak (concert) - Umm Kulthum اغدا القاك (حفلة) - ام كلثوم",
  "41": "Agheb W Zo Al Lataef La Yagheb",
  "42": "Aghrab",
  "43": "Ah Min El Hawa",
  "44": "Ah Minak Ya Habibi",
  "45": "Ah Minel Sabr",
  "46": "Ah Ya Ayni",
  "47": "Ah Ya Lli",
  "48": "Ah Ya Oum Hamada",
  "49": "Ahbabna Ya Ein - Farid Al-Atrash  أحبابنا يا عين - فريد الأطرش",
  "50": "Ahebaha Fateya Zakia Arabeya",
  "51": "Ahen Eleik - Abdel Halim Hafez احن اليك - عبد الحليم حافظ",
  "52": "Ahib Icht El Horria (Original Mix)",
  "53": "Ahl El Hawa",
  "54": "Ahlan Beil Shams",
  "55": "Akd El Fol",
  "56": "Akhaf Minnak",
  "57": "Akoul wakad nahat",
  "58": "Aktar Min Malyoun",
  "59": "Al Ataba Al Baalbakieh",
  "60": "Al Bouab",
  "61": "Al Dalouna",
  "62": "Al Haer",
  "63": "Al Hawa Wal Chabab (Original Mix)",
  "64": "Al Heila Heila",
  "65": "Al Karnak",
  "66": "Al Khael Ala El Maia",
  "67": "Al Makla",
  "68": "Al Masjid Al Aksa",
  "69": "Al Salihie",
  "70": "Al Yani El Yani",
  "71": "Al foul wil yassmine (Live)",
  "72": "Al-Bir",
  "73": "Al-Qlb Dab",
  "74": "Al-ouzoubïa (Live)",
  "75": "Ala Ad El Leil",
  "76": "Ala Ad El Shouq - Abdel Halim Hafez على قد الشوق - عبد الحليم حافظ",
  "77": "Ala Ain El May Ya Samra",
  "78": "Ala Allah Yaboy",
  "79": "Ala Balad El Mahbob - Umm Kulthum على بلد المحبوب - ام كلثوم",
  "80": "Ala Balad El Morsy Abo El Abas",
  "81": "Ala Baly Ya Kamar",
  "82": "Ala Biir Ettay",
  "83": "Ala Chebbak El Helwi",
  "84": "Ala El Remal",
  "85": "Ala Jisr El Laouzieh",
  "86": "Ala Keyfi",
  "87": "Ala Khadha Khal",
  "88": "Ala Mafrak Darb El Habayeb",
  "89": "Ala Masrahek Ya Donya",
  "90": "Ala Nabeh El May",
  "91": "Ala Nour El Fawanes",
  "92": "Ala Wara El Ward",
  "93": "Ala Ward We Fol",
  "94": "Alaa Kaffy",
  "95": "Alaab Maa El Beid",
  "96": "Alah Yegazeek - Warda الله يجازيك - وردة",
  "97": "Alali Addar",
  "98": "Alashan El Shook - Mohamed Abd El Wahab علشان الشوك - محمد عبد الوهاب",
  "99": "Alby El Shaai",
  "100": "Aleim Allah",
  "101": "Alein",
  "102": "Alemhatta",
  "103": "Alfein Salam",
  "104": "Allah Thalethna - Mohamed Abd El Wahab الله ثالثنا - محمد عبد الوهاب",
  "105": "Allawy Allawy",
  "106": "Allo Shtaetellak",
  "107": "Almaadi (Original Mix)",
  "108": "Almamalik (Original Mix)",
  "109": "Almanjera",
  "110": "Am Tegzel",
  "111": "Amana Alek",
  "112": "Amana Ya Bokra",
  "113": "Amana Ya Leil (Original Mix)",
  "114": "Amar",
  "115": "Amira Live - Sayed Mekawy أميره تسجيل حفلة - سيد مكاوي",
  "116": "Amm Tekbar Lfarha",
  "117": "Ana Abdak Ala 3ahdak",
  "118": "Ana Ad Kalamy",
  "119": "Ana Bamassi",
  "120": "Ana Bamassy",
  "121":
    "Ana Fe Entezarak 2 Live - Sayed Mekawy أنا في إنتظارك 2 تسجيل حفلة - سيد مكاوي",
  "122": "Ana Haweitak",
  "123": "Ana Hawet",
  "124":
    "Ana Hena Ya Ebn El Halal Live - Sayed Mekawy أنا هنا يا ابن الحلال تسجيل حفلة - سيد مكاوي",
  "125":
    "Ana Kont Fakrak Malak - Farid Al-Atrash  أنا كنت فاكرك ملاك - فريد الأطرش",
  "126": "Ana Msh Nasy",
  "127": "Ana Saraak",
  "128": "Ana Sayad",
  "129": "Ana Welly Bahebo - Farid Al-Atrash  أنا واللي بحبه - فريد الأطرش",
  "130": "Ana hawet ou ntahet",
  "131":
    "Andak Shak Fi Eih - Sayed Mekawy عندك شك فى إيه تسجيل حفلة - سيد مكاوي",
  "132": "Aqbal Al Laylo - Umm Kulthum اقبل الليل - ام كلثوم",
  "133":
    "Arak Asey Al Damaa (concert) - Umm Kulthum اراك عصى الدمع (حفلة) - ام كلثوم",
  "134": "Arak Asey El Damaa - Umm Kulthum اراك عصى الدمع - ام كلثوم",
  "135": "Arapça İlahi 4",
  "136": "Arrem Ya Joukh",
  "137":
    "AsbahAndyAlAnBondokeya - Mohamed Abd El Wahab أصبح عندىالأن بندقية - محمد عبد الوهاب",
  "138": "Ashan Alby Byehwak",
  "139": "Ashara Ala Ashara",
  "140": "Ashkar We Shaaro Dahab",
  "141": "Ashky Le Men Gherak",
  "142": "Asleh Еl Awtar",
  "143": "Asmahan - Ahwa",
  "144": "Asmahan - Alik salat allah أسمهان‎",
  "145": "Asmahan - Askiniha",
  "146": "Asmahan - Elouyoun",
  "147": "Asmahan - Elward",
  "148": "Asmahan - Emta tioud",
  "149": "Asmahan - Enta hataraf أسمهان‎",
  "150": "Asmahan - Konti elamani",
  "151": "Asmahan - Layta lel barrak",
  "152": "Asmahan - Sahirtou toul el leil",
  "153": "Asmahan - Ya habibi taala elhaani",
  "154": "Asmahan - Ya touyour أسمهان‎",
  "155": "Asmahan - Yalli hawak",
  "156": "Asmar Kahil El Ein",
  "157": "Asmar Yakhi",
  "158": "Asmarany",
  "159": "Asmrany",
  "160": "Asr Al-Hwy",
  "161": "Asr El Hawa",
  "162": "Assiba Ouel Jamal (Original Mix)",
  "163": "Atena Le Bab El Hoda",
  "164": "Atshan",
  "165": "Awaaty Betehlaw - Sayed Mekawy أوقاتي بتحلو معاك - سيد مكاوي",
  "166": "Awaaty Betehlaw Live - Sayed Mekawy أوقاتي بتحلو - سيد مكاوي",
  "167": "Aweel Ibtissama",
  "168": "Awel Mara - Abdel Halim Hafez اول مره تحب ياقلبى - عبد الحليم حافظ",
  "169": "Awsefak - Warda أوصفك - وردة",
  "170":
    "Ay Damaet Hozn La (Short version) - Abdel Halim Hafez اي دمعة حزن لا (نسخة قصيرة) - عبد الحليم حافظ",
  "171": "Ay Shay ناظم الغزالي - أي شيء",
  "172": "Ay She Menak Yesry",
  "173": "Ay shay fi aleid",
  "174": "Ayad El Eid",
  "175": "Ayam El Remsh El Makhoul",
  "176": "Ayami (Original Mix)",
  "177": "Ayaratni Bi-Shaib",
  "178": "Ayaratni bilshaib",
  "179": "Ayez Gawabatak",
  "180": "Ayoha El Sary - Mohamed Abd El Wahab إيها السارى - محمد عبد الوهاب",
  "181": "Aysh turid nuqaddim lak hadia",
  "182": "BAYAA ELHAWA",
  "183": "BETOLY BAHEBK MEN EMTA",
  "184": "BETSLENY BAHEBK LEH",
  "185": "Baadak Ala Baly",
  "186": "Baadak Ya Amarna",
  "187": "Baddi Choufik Koul Yom",
  "188": "Baddi Helwi",
  "189": "Badry Ya Lail El Shoq",
  "190": "Bafakar Filli Nassini (Original Mix)",
  "191": "Baheb El Asmar",
  "192": "Bahr El Akaba",
  "193": "Bakir Baadek",
  "194": "Baladi Habibi",
  "195": "Balash tebousni faanaya",
  "196":
    "Banady Aliek - Lahn El Kholod - Farid Al-Atrash بنادي عليك - لحن الخلود - فريد الأطرش",
  "197":
    "Banady Aliek Live Record - Farid Al-Atrash بنادي عليك تسجيل حفلة - فريد الأطرش",
  "198": "Banati Ya Anb",
  "199": "Banota",
  "200": "Barada Barada",
  "201": "Barbar Agha",
  "202": "Barkoly",
  "203": "Batal El Thawra - Mohamed Abd El Wahab بطل الثورة - محمد عبد الوهاب",
  "204": "Batalt El Hob",
  "205": "Bayn Eddawaly",
  "206": "Be Eionak Fe Sora",
  "207": "Behbak",
  "208": "Beil Ams Ya Weilha",
  "209":
    "Beiny We Beinak Eh - Abdel Halim Hafez بينى وبينك ايه - عبد الحليم حافظ",
  "210": "Bellah Tesobo Ha El Kahwa",
  "211": "Bessaha Tlakayna",
  "212": "Bezaf Barkoly",
  "213": "Bi Karm El Loulou",
  "214": "Bidha Tountor",
  "215": "Bieghfa Llayle",
  "216": "Bil Kattara Bil Kattara",
  "217": "Bilamara Labnilik Bait",
  "218": "Bileil Ya Rohi (Original Mix)",
  "219": "Bilsaha Tlaqayna",
  "220": "Biya Wala Beek",
  "221": "Biyfrigha Allah",
  "222": "Bizet Carol",
  "223": "Bokra Bokra",
  "224": "Bolbol Hayran (Original Mix)",
  "225":
    "Bosat El Reeh Live Record - Farid Al-Atrash  بساط الريح تسجيل حفلة - فريد الأطرش",
  "226": "Boulboul Haïran",
  "227": "Btezkor Ya Albi",
  "228": "Byelbalek",
  "229": "Chaka Chiko",
  "230": "Chefta W Janayt",
  "231": "Cherwal Jeddak Ya Jeddi",
  "232": "Cherwal Jeddak Ya Jeddi 2",
  "233": "Chihate Al Gharame",
  "234": "Chihate El Gharam",
  "235": "Chou Bkoul La Ahli",
  "236": "Chou Byehla El Maghna",
  "237": "Chou Helwe Ya Sinin",
  "238": "Cleopatra (Pt 1) (Original Mix)",
  "239": "Cleopatra (Pt 2) (Original Mix)",
  "240": "Daa Wa Daa",
  "241": "Daah We Daah",
  "242": "Daai El Azoul",
  "243":
    "Daeat Saat El Amal - Mohamed Abd El Wahab دقت ساعة العمل - محمد عبد الوهاب",
  "244": "Dael Habib Daa",
  "245": "Dahb Ma Bady Dahb",
  "246": "Dakhlek Wal Hawa",
  "247": "Dana Habayte",
  "248": "Dar El Oyoune",
  "249": "Darabny We Baka",
  "250": "Darb El Ghezlane",
  "251": "Daro Osad Dary",
  "252": "Dasit Manadil",
  "253": "Dawal hawa kanadilou",
  "254": "Dawrouli An Habib",
  "255": "Dekra",
  "256": "Delwakt Geat",
  "257": "Demou Einy",
  "258": "Dhaheit Gharami (From Al Warda Al Baidha) (Original Mix)",
  "259": "Dmw Ayny",
  "260": "Doko El Mazaher - Farid Al-Atrash  دقوا المزاهر - فريد الأطرش",
  "261": "Dore Ya Donya",
  "262": "Doroup El Hawa",
  "263": "Dory Dory",
  "264": "Doumoua Ouyouni",
  "265": "Duaa Ya Rab",
  "266": "EH HOA DA",
  "267": "EHNA KONA ASHAB",
  "268": "ELLILA DED",
  "269": "ELMRTAHEN FE ELHOB",
  "270": "ELSABT FAAT",
  "271": "ESHTTTLAK",
  "272": "Eagry Ya Nile - Mohamed Abd El Wahab إجري يا نيل - محمد عبد الوهاب",
  "273": "Eayrtani bialsh shayb",
  "274": "Ebied Any Oyonak Live Record",
  "275": "Echtana",
  "276": "Efrah Eross",
  "277": "Efrah Ya Qalby - Umm Kulthum افرح ياقلبى - ام كلثوم",
  "278":
    "Egmaay Ya Misr (Melad El Malek) - Umm Kulthum اجمعى يامصر( ميلاد الملك ) - ام كلثوم",
  "279": "Eh El Dawa Ll Hob",
  "280": "Eh Enkatebli",
  "281": "Ehna Kona Fein - Abdel Halim Hafez احنا كنا فين - عبد الحليم حافظ",
  "282": "Ehtar Khayaly - Abdel Halim Hafez احتار خيالى - عبد الحليم حافظ",
  "283": "Eicha Ou Choufna",
  "284": "Eid El Milad",
  "285": "Eid Thawrtna",
  "286": "Einy Addaky El Noum",
  "287": "Eionak",
  "288": "Eksab Halal Ya Zain",
  "289": "El Ab",
  "290": "El Alb Dab",
  "291":
    "El Ard Betetkalem Araby Live - Sayed Mekawy الأرض بتتكلم عربى - سيد مكاوي",
  "292": "El Ard El Tayeba",
  "293":
    "El Ayam El Helwa Live - Sayed Mekawy الايام الحلوة تسجيل حفلة - سيد مكاوي",
  "294": "El Azary El Maessat",
  "295": "El Bahr Kan Atshan",
  "296": "El Ein Basira",
  "297": "El Gadayel",
  "298":
    "El Geal El Saed - Mohamed Abd El Wahab الجيل الصاعد - محمد عبد الوهاب",
  "299": "El Ghaly",
  "300": "El Ghaly Live - Sayed Mekawy الغالي تسجيل حفلة - سيد مكاوي",
  "301": "El Hawa Yomma",
  "302": "El Hawan Wayak (Original Mix)",
  "303": "El Hayah Helwa - Farid Al-Atrash الحياه حلوه - فريد الأطرش",
  "304": "El Hilwi Li Chaghil Bali",
  "305": "El Hop Lahn Gameel - Farid Al-Atrash الحب لحن جميل - فريد الأطرش",
  "306": "El Horiya",
  "307": "El How Dlany",
  "308": "El Karnak - Mohamed Abd El Wahab الكرنك - محمد عبد الوهاب",
  "309": "El Kelal El Kenawy",
  "310": "El Layali - Abdel Halim Hafez الليالى - عبد الحليم حافظ",
  "311": "El Leila El Kebira - Sayed Mekawy الليلة الكبيرة - سيد مكاوي",
  "312": "El Mared El Arabi - Farid Al-Atrash المارد العربى - فريد الأطرش",
  "313":
    "El Moseka El 3arabeya -  Khafef El Ro7  الموسيقي العربيه - خفيف الروح",
  "314":
    "El Nahr El Khaled Music - Mohamed Abd El Wahab موسيقى النهر الخالد - محمد عبد الوهاب",
  "315":
    "El Nahr El Khaled- Mohamed Abd El Wahab النهرالخالد(وطنيات2) - محمد عبد الوهاب",
  "316": "El Omr Kolo Yomen",
  "317": "El Qahwa",
  "318": "El Qalbi Dab",
  "319":
    "El Rabeaa Live Record - Farid Al-Atrash الربيع تسجيل حفلة - فريد الأطرش",
  "320": "El Rabieaa - Farid Al-Atrash الربيع - فريد الأطرش",
  "321":
    "El Rawaby El khodr - Mohamed Abd El Wahab الروابى الخضر - محمد عبد الوهاب",
  "322":
    "El Saber We El Eman - Mohamed Abd El Wahab الصبروالأيمان - محمد عبد الوهاب",
  "323": "El Shahead - Mohamed Abd El Wahab الشهيد - محمد عبد الوهاب",
  "324": "El Shams El Garea",
  "325": "El Shaytan",
  "326": "El Sheikh Massoud",
  "327": "El Ward Gamiel Live - Sayed Mekawy الورد جميل تسجيل حفلة - سيد مكاوي",
  "328": "El Ward Gamil - Sayed Mekawy الورد جميل - سيد مكاوي",
  "329":
    "El Watan El Akbar - Mohamed Abd El Wahab الوطن الأكبر - محمد عبد الوهاب",
  "330":
    "El Watan El Akbar Oud - Mohamed Abd El Wahab الوطن الأكبر عود - محمد عبد الوهاب",
  "331": "El Zaman Nassay",
  "332":
    "ElYomFataht Eany - Mohamed Abd El Wahab اليوم فتحت عيني - محمد عبد الوهاب",
  "333": "Ela Alnnasr",
  "334":
    "Elly Enshaghalt Aleih - Abdel Halim Hafez اللى انشغلت عليه - عبد الحليم حافظ",
  "335": "Enaya Betedhak - Farid Al-Atrash عيني بتضحك  - فريد الأطرش",
  "336":
    "Enaya Mahma Kalo Anak Live Record - Farid Al-Atrash عيني مهما قالو عنك حفلة - فريد الأطرش",
  "337": "Ennaby Ya Khdoudi El Hiliwa",
  "338": "Ennahr Elkhaled (Original Mix)",
  "339": "Enta Rfiki",
  "340": "Entahena - Warda إنتهينا - وردة",
  "341": "Enti Lwahideh",
  "342": "Eref El Shoq Ywsaly",
  "343": "Eref El Shoq Ywsaly Hafla",
  "344": "Esaal Marra Alaya - Sayed Mekawy أسأل مرة عليا - سيد مكاوي",
  "345": "Esh Anta - Farid Al-Atrash عش انت حفلة  - فريد الأطرش",
  "346": "Eshak Ya Bolbol - Farid Al-Atrash  عشك يابلبل - فريد الأطرش",
  "347": "Eshna Wei Shofna",
  "348": "Eshtakna Ktir",
  "349": "Eshtakna a Loubnan",
  "350": "Esmah - Farid Al-Atrash  قسمه - فريد الأطرش",
  "351": "Esmaouni",
  "352": "Essetna Gharibe",
  "353": "Estana",
  "354": "Etnashar Youm Ya Ghaddara",
  "355": "Eyak Men Hoby - Farid Al-Atrash إياك من حبى - فريد الأطرش",
  "356": "Eyoun El Narjis",
  "357": "Ezkoreeny - Umm Kulthum اذكرينى - ام كلثوم",
  "358": "Ezoulm Da Kan Leih (Original Mix)",
  "359": "FE ALBY GRAM",
  "360": "Fairuz -  Ana Khaoufi",
  "361": "Fairuz - Attahuneh",
  "362": "Fairuz - Jayebli Salam",
  "363": "Fairuz - Katabna Ou Ma Katabna",
  "364": "Fairuz - Lamma Al Bab",
  "365": "Fairuz - Min Ezz Ennoum Btesrekni",
  "366": "Fairuz - Sayyef Ya Sayf",
  "367": "Fairuz - Tiri Ya Tayara",
  "368": "Fairuz - Ya Dara Douri Fina",
  "369": "Fairuz - Ya Karm El Alaly",
  "370": "Fairuz - Ya Mersal El Marassil",
  "371": "Fairuz - Ya Rayt Mennon",
  "372": "Fallah",
  "373": "Farash Wa Zahra",
  "374": "Farid el Atrache - Halfi ana",
  "375": "Farid el Atrache - Houbbar",
  "376": "Farid el Atrache - Mahaqdar",
  "377": "Farid el Atrache - Yigi yom",
  "378": "Farid el Atrache - Yom mmen",
  "379": "Fark El Seneen - Warda فرق السنين - وردة",
  "380": "Fatma Wma Ryka Wrashyl",
  "381": "Fatouma",
  "382": "Fawq al nakl",
  "383": "Fayek Ya Hawa",
  "384": "Fayrouz - A3teny Al Nay  فيروز - أعطنى الناى",
  "385": "Fayrouz - Akher Eyam El Saifeia  فيروز - أخر أيام الصيفية",
  "386": "Fayrouz - Ana Sar Lazem Wadekon  فيروز -أنا صار لازم ودعكن",
  "387": "Fayrouz - El Bosta  فيروز - البوسطة",
  "388": "Fayrouz - Habaitak Belsaif  فيروز - حبيتك بالصيف",
  "389": "Fayrouz - Habaitak Wel Shawq Enqal  فيروز - حبيتك و الشوق إنقال",
  "390": "Fayrouz - Habo Bad  فيروز - حبو بعض",
  "391": "Fayrouz - Kefak Enta  فيروز - كيفك إنتا",
  "392": "Fayrouz - Nahna Wel Qamar Jeran  فيروز - نحنا والقمر جيران",
  "393": "Fayrouz - Oudak Ranan  فيروز - عودك رنان",
  "394": "Fayrouz - Raj3ein Ya Hawa  فيروز - راجعين يا هوا",
  "395": "Fayrouz - Saalouny El Nas  فيروز - سألونى الناس",
  "396": "Fayrouz - Saaltak Habiby  فيروز - سألتك حبيبى",
  "397": "Fayrouz - Sahr El Layaly  فيروز - سهر الليالى",
  "398": "Fayrouz - Salemly Aleah  فيروز - سلملي علية",
  "399": "Fayrouz - Shady  فيروز - شادى",
  "400": "Fayrouz - Shaief El Bahr  فيروز - شايف البحر",
  "401": "Fayrouz - Shat Eskenderia  فيروز - شط إسكندرية",
  "402": "Fayrouz - Shaty Ya Denya  فيروز - شتى يا دنيا",
  "403": "Fayrouz - Teri Ya Tayara  فيروز - طيري يا طيارة",
  "404": "Fayrouz - Ya Ana Ya Ana  فيروز - يا أنا يا أنا",
  "405": "Fayrouz - Ya Mekhtar El Makhater  فيروز - يا مختار المخاتير",
  "406": "Fayrouz - Zorony  فيروز - زورونى",
  "407":
    "Fe Yom Men El Ayam - Abdel Halim Hafez فى يوم من الايام - عبد الحليم حافظ",
  "408": "Fein Ayamak - Warda فين ايامك - وردة",
  "409": "Fesstani",
  "410": "Fik Nass Ya Leil",
  "411": "Fik Nass Ya Lil",
  "412": "Fin Habibi Elly Fi Khayali",
  "413": "Fin Kalbi",
  "414": "Firrode ana shouft (Live)",
  "415": "Fog Nakhel",
  "416": "Fouk El Nakhel",
  "417":
    "Fouk Ghosnek Ya Lamona - Farid Al-Atrash فوق غصنك يا ليمونة حفلة - فريد الأطرش",
  "418": "Fouk el nakhal",
  "419": "Frasha Wa Zahra",
  "420": "Fyk Nas Yalyl",
  "421": "Gady",
  "422": "Gafnouhou (From Al Warda Al Baidha) (Original Mix)",
  "423": "Gamiel Gamal - Farid Al-Atrash  جميل جمال - فريد الأطرش",
  "424": "Gawabati - Warda جواباتي - وردة",
  "425": "Gennili Bellil",
  "426": "Ghabit Al-Shams",
  "427": "Ghanna Rabibi-lisan at-Tayr",
  "428": "Ghany Ya Alby - Farid Al-Atrash غني يا قلبى - فريد الأطرش",
  "429": "Gharabou Hwali",
  "430": "Ghariba",
  "431": "Ghariba Ageeba Hekayet Alby",
  "432": "Go Tell It on the Mountain",
  "433": "God Rest Ye Merry Gentlemen",
  "434": "Guiyabak Tal",
  "435": "HABETK WBHEBAK",
  "436": "HABIBE YOM SAFRO",
  "437": "Habayebna Hawalayna",
  "438": "Habbaytak Inta Wou Bass",
  "439": "Habbebi Yesead Awkato - Sayed Mekawy حبيبي يسعد أوقاته - سيد مكاوي",
  "440": "Habbet Houboubann Chemali",
  "441": "Habeby Dammeny Damma",
  "442": "Habeeb Hayaty - Abdel Halim Hafez حبيب حياتى - عبد الحليم حافظ",
  "443": "Habet Eyal Maganin",
  "444":
    "Habeto Laken Mabaqlshy - Farid Al-Atrash  حبيته لكن مابقلش - فريد الأطرش",
  "445": "Habibi",
  "446": "Habibi Domeni Dama",
  "447": "Habibi Hall Fni Qalbi Aji Alak",
  "448": "Habibi Han",
  "449": "Habibi Lasmar (Original Mix)",
  "450": "Habibi aladdounya (Live)",
  "451": "Habiby Domeny Damma",
  "452": "Habiby Yesaed Awaato - Sayed Mekawy حبيبي يسعد أوقاته - سيد مكاوي",
  "453": "Habieb El Omr - Farid Al-Atrash  حبيب العمر - فريد الأطرش",
  "454": "Hadda Lheyl",
  "455": "Haddoni",
  "456": "Hal Hilalak",
  "457": "Hala Bi Emm Al Ouyoun Al Soud",
  "458": "Hala Ya Hala",
  "459": "Hala Ya Reem",
  "460": "Halet Layaly Helwa - Farid Al-Atrash هلت ليالي حلوه - فريد الأطرش",
  "461": "Halhilween",
  "462": "Hallailah",
  "463": "Hammaltak Salami",
  "464": "Hanna Leil Saif",
  "465": "Hanneit Lak",
  "466": "Harag Alaya Baba",
  "467": "Haram Ya Nar - Abdel Halim Hafez حرام يانار - عبد الحليم حافظ",
  "468": "Hassadouna El Nass",
  "469": "Hat El Hob",
  "470": "Hati Hati Ya Dikrayati",
  "471": "Hatohat",
  "472": "Hawaa",
  "473": "Hawel Teftakerni",
  "474":
    "Hay Ala El Falah - Mohamed Abd El Wahab حي علي الفلاح - محمد عبد الوهاب",
  "475": "Hay El Ommal",
  "476": "Hayak Baba Hayak",
  "477": "Hayhat Yetellou El Helwine",
  "478": "Hayya Hayya",
  "479": "Hazz El Haya",
  "480": "Hazzi El Hayat",
  "481": "Hegret Al Rasol",
  "482": "Heh! Heh! Baba",
  "483":
    "Hekayet Gharamy Live Record - Farid Al-Atrash حكإيه غرامي حفلة - فريد الأطرش",
  "484": "Helw We Kadab - Abdel Halim Hafez حلو وكداب - عبد الحليم حافظ",
  "485": "Helwa",
  "486": "Helwa Ya Niyalha",
  "487": "Henna Ya Henna",
  "488": "Hetet Sokar Live",
  "489":
    "Heya Di El Mahabba Live - Sayed Mekawy هى دي المحبة تسجيل حفلة - سيد مكاوي",
  "490": "Hezz El Hellal",
  "491": "Hiak baba an hiak",
  "492": "Hidaya Hidaya",
  "493": "Hikaiti Maa Elghram",
  "494": "Hlemt Behoreah",
  "495": "Hobak Salehne",
  "496": "Hobbak kadar - Warda حبك قدر - وردة",
  "497": "Hobby Rahal",
  "498": "Hopy Rahl",
  "499":
    "Horeyat Aradena - Mohamed Abd El Wahab حرية أراضينا - محمد عبد الوهاب",
  "500": "Hourouf El Hob",
  "501": "Howa Bas Howa - Farid Al-Atrash  هو بس هو  - فريد الأطرش",
  "502": "Hz Al-Hyah",
  "503": "Iddounia Hobb",
  "504": "Igri Igri",
  "505": "Igri Igri (Original Mix)",
  "506": "Ihna Ishab",
  "507": "Ijana Aam Men Al Argentine",
  "508": "Il Est Ne Le Divin Enfant",
  "509": "Indama Yaati Al Massaa (Original Mix)",
  "510": "Indy Hal Aalb",
  "511": "Inn Lansoub Telephone",
  "512": "Instrumental",
  "513": "Intro",
  "514": "Introduction",
  "515": "Iref Chouq Yousali",
  "516": "Irzalna Al-Akhdar",
  "517": "Iskandaria",
  "518": "Jabal Horan",
  "519": "Jaddely Yam Jadayel",
  "520": "Jani Eli Behibah",
  "521": "Jawwazouni",
  "522": "Jayine Min Blad El Gherbe",
  "523": "Jaysh Biladi",
  "524": "Joy to the World",
  "525": "Kaab El Bent Reyal Meddawar",
  "526": "Kaabi Ezzin",
  "527": "Kaed Liwahdak",
  "528": "Kamar El Zaman - Farid Al-Atrash قمر الزمان - فريد الأطرش",
  "529": "Kan Badri Alik",
  "530":
    "Kan Fi Zaman Albein - Abdel Halim Hafez كان فيه زمان قلبين - عبد الحليم حافظ",
  "531": "Kanou Ya Habiby",
  "532": "Kanou zeghar",
  "533": "Kant Zgery",
  "534": "Karem Mahmoud  - Baedan  كارم محمود - بعيدا",
  "535": "Karem Mahmoud -  Atshan Ya Eskndreya  كارم محمود - عطشان يا اسكندريه",
  "536": "Karem Mahmoud - 3enaby  كارم محمود - عنابي",
  "537": "Karem Mahmoud - Agelak Men Hena  كارم محمود - أجيلك من هنا",
  "538":
    "Karem Mahmoud - Ala Shat Bahr El Hawa  كارم محمود  - على شط بحر الهوى",
  "539": "Karem Mahmoud - Ala Waraa El Ward  كارم محمود - على ورق الورد",
  "540": "Karem Mahmoud - Amana 3lik  كارم محمود - أمانة عليك",
  "541": "Karem Mahmoud - Einy Bitrif  كارم محمود - عينى بترف",
  "542": "Karem Mahmoud - El Atota  كارم محمود - القطقوطه",
  "543":
    "Karem Mahmoud - El Hawa Maktoob Alena  كارم محمود - الهوى مكتوب علينا",
  "544": "Karem Mahmoud - Le Had Bokra  كارم محمود - لحد بكرا",
  "545": "Karem Mahmoud - Samra Ya Samra   كارم محمود - سمرا يا سمرا",
  "546": "Karem Mahmoud - We Naby Ya Gamil  كارم محمود - والنبى يا جميل",
  "547":
    "Karem Mahmoud - Ya Mhayer Alb Mohbinak  كارم محمود - يا محير قلب محبينك",
  "548": "Karem Mahmoud - Yana Ya El Ozal  كارم محمود - يا أنا يا العزال",
  "549": "Kassim Charki Baladi",
  "550": "Kayfa Marat ala Hawaka al Kouloub",
  "551": "Kberet Wi Oumri Kbir",
  "552": "Kedna Ya Amarna",
  "553": "Kenna Chi Miyi Wkhamssin",
  "554": "Kenna Tleti",
  "555": "Khaf Alaya",
  "556": "Khaleha Ala Allah - Farid Al-Atrash خليها علي الله - فريد الأطرش",
  "557":
    "Khalleny Akhrog Men Hena - Farid Al-Atrash خلليني اخرج من هنا - فريد الأطرش",
  "558": "Khallik Hena",
  "559": "Khallik a Sawa",
  "560": "Khallina Aachikin",
  "561": "Khally Shwaya Aliek - Sayed Mekawy خلي شوية عليك - سيد مكاوي",
  "562": "Khamrat El Hob",
  "563": "Khasemteny - Umm Kulthum خاصمتنى - ام كلثوم",
  "564": "Khatarna Ala Balak",
  "565": "Khay Khay - Mohamed Abd El Wahab خي خي - محمد عبد الوهاب",
  "566": "Khayef Aleiha",
  "567": "Khayef Aqoul (Original Mix)",
  "568": "Khayef aleha",
  "569": "Khayf ealayha",
  "570": "Kheles elkalam",
  "571": "Khelli Alhawa",
  "572": "Khody Alby - Farid Al-Atrash  خدي قلبى - فريد الأطرش",
  "573": "Kif Halon",
  "574": "Kol Akh Araby - Mohamed Abd El Wahab كل أخ عربى - محمد عبد الوهاب",
  "575":
    "Kol Ma Yezdad Rda Albak - Umm Kulthum كل ما يزداد رضا قلبك - ام كلثوم",
  "576":
    "Kol Mara Lamma Awaadak Live - Sayed Mekawy كل مرة لما أواعدك - سيد مكاوي",
  "577":
    "Kolly Amalak Eh - Mohamed Abd El Wahab قوللي عملك إيه - محمد عبد الوهاب",
  "578": "Kololy Shlon",
  "579": "Koloo Lemasr - Mohamed Abd El Wahab قولو لمصر - محمد عبد الوهاب",
  "580": "Konna Netlaka",
  "581": "Koul Elli Hab Intassaf (Original Mix)",
  "582": "Kouli ya helou",
  "583": "Koullina Nahib Al Qamar (Original Mix)",
  "584": "La Inta Radhi",
  "585": "La La La La La",
  "586": "La La Llouli La La",
  "587": "La La Loh La La",
  "588": "La Lee",
  "589":
    "La Mosh Ana Ely Abky- Mohamed Abd El Wahab لأمش أنااللي أبكي - محمد عبد الوهاب",
  "590": "La Talomny - Abdel Halim Hafez لا تلومني - عبد الحليم حافظ",
  "591": "La Ya Habebe",
  "592": "La khal ala Safahat khad",
  "593": "Labaik Ya Allah",
  "594": "Labayk",
  "595": "Lah Tayf El Hassan",
  "596": "Lahn El Wafaa - Abdel Halim Hafez لحن الوفاء - عبد الحليم حافظ",
  "597": "Laila",
  "598": "Laila Nazmy  - Mn El Sanawya LlKolia  ليلي نظمي - من الثانوية للكليه",
  "599":
    "Laktob Ala Awrak El Shagar - Farid Al-Atrash لكتب ع وراق الشجر - فريد الأطرش",
  "600":
    "Laktob Ala Awrak El Shagar - Farid Al-Atrash موال لكتب ع وراق الشجر - فريد الأطرش",
  "601": "Lam Taod Zakiran",
  "602": "Lamma Bissirou Tmentaach",
  "603": "Lamma Kenet Zghiri",
  "604": "Lammadhekti Dahhaktina",
  "605": "Laoulaki Ya Malaki",
  "606": "Larkab Haddek Bel Motor",
  "607": "Law Kent Mjawaz",
  "608":
    "Law Kont Yom Ansak - Abdel Halim Hafez لو كنت يوم انساك - عبد الحليم حافظ",
  "609":
    "Law Kont Youm Ala Alby Tehoun - Abdel Halim Hafez لو كنت يوم على قلبى تهون - عبد الحليم حافظ",
  "610": "Law Tefreshli El Ardi Henna",
  "611": "Layali Loubnan (Original Mix)",
  "612": "Layat Hagerry - On Oud",
  "613": "Leah Ana Bahebak - Farid Al-Atrash  ليه أنا بحبك - فريد الأطرش",
  "614": "Leih Ya Mahboub",
  "615": "Leih Ya Zaman - Umm Kulthum ليه يا زمان - ام كلثوم",
  "616": "Leilat El Wadaa (Original Mix)",
  "617": "Lesa Bahebak Pt 1",
  "618": "Lesa Bahebak Pt 2",
  "619": "Lesa Bahebak Pt 3",
  "620": "Lesa Bahebak Pt 4",
  "621": "Lesa Bahebak Pt 5",
  "622": "Lesa Bahebak Pt 6",
  "623": "Lesa Bahebak Pt 7",
  "624": "Leyleye Bterjaa Ya Leyl",
  "625": "Lih Ya Banasej",
  "626": "Lildhaif Maftuha Manazilna",
  "627": "Lobnan Fawk El-Ard",
  "628": "Lubnan Ya Qitit Sama",
  "629": "MESTNY GAWAB",
  "630": "Ma Ahla Al Habib (Original Mix)",
  "631": "Ma Akdar Akollak",
  "632": "Ma Akdar Owadiaahom",
  "633": "Ma Chaka Albi",
  "634": "Ma Kan Loon Alward",
  "635": "Ma Qaly We Qoltelo - Farid Al-Atrash ماقاللي وقلتله - فريد الأطرش",
  "636": "Ma Tekhabbar Hadda",
  "637": "Maak Ya Omry",
  "638": "Maaoula Halawtak Di (live)",
  "639": "Mabaaref",
  "640": "Mabrouk Aleiky Ya Meegebany",
  "641": "Mabrouk Aleina",
  "642":
    "Maddah El Qamar(Short version) - Abdel Halim Hafez مداح القمر - عبد الحليم حافظ",
  "643": "Maeoola",
  "644": "Magareh",
  "645": "Mahbobeh",
  "646": "Mahla El Habib (Original Mix)",
  "647": "Mahma Yetjarrah Lebnan",
  "648": "Makdarsh Ala Kida",
  "649": "Maksar Assa",
  "650": "Mal Wei Ethageb",
  "651": "Malaksh Hak - Farid Al-Atrash مالكش حق - فريد الأطرش",
  "652": "Mane hakak",
  "653": "Maoulid Ennour (Original Mix)",
  "654": "Maqdar Akollak",
  "655":
    "Marakoul hassadeen  Yamme ma baref  Rah halfak ya tayr  Moussalha (Medley)",
  "656": "Marhab Hala",
  "657": "Marhab Marhab",
  "658":
    "Marhab Marhab Marhabtein - Farid Al-Atrash  مرحب مرحب مرحبتين - فريد الأطرش",
  "659": "Marjeh Ya Hawa",
  "660": "Marrit Aala Beit El Habayeb (Original Mix)",
  "661":
    "Mashghool Wehyatek - Abdel Halim Hafez مشغول وحياتك - عبد الحليم حافظ",
  "662": "Mashi El Helou",
  "663": "Masica Ya Masica",
  "664": "Matensanash Pt 1",
  "665": "Matensanash Pt 2",
  "666": "Matensanash Pt 3",
  "667": "Matensanash Pt 4",
  "668": "Mawal El Oshak",
  "669": "Mawal Oul Lel Maliha",
  "670": "Mawasem - Warda مواسم - وردة",
  "671":
    "Mawood (Short version) - Abdel Halim Hafez موعود  تسجيل حفلة (نسخة قصيرة) - عبد الحليم حافظ",
  "672": "Mawoud",
  "673": "Mayel Ya Ghezayel",
  "674": "Mech Mhem",
  "675": "Medayye Albi Ou Omri",
  "676":
    "Medley Mawal Min Khamret Elhob  Zaman Zaman  Lamouni Al Leimouni  El Kerrasia",
  "677": "Medley Mouwachah Imlili  Ya Chadi El Alhan",
  "678":
    "Medley Takassim  Fawk El Nakhl  El Boulbol Nam a Ghosn El Foll  Takassim  Mouwachahat &",
  "679":
    "Medley Takassim  Mawal Fattah Bikhadak Wouroud  Mili Ma Mal El Hawa  Takassim Mawal Min Yom",
  "680": "Medley Ya Hadi Al Les  Malek Ya Helwa Malek",
  "681": "Meen Yeaaraf - Farid Al-Atrash مين يعرف  - فريد الأطرش",
  "682": "Mehtar Ya Nass - Umm Kulthum محتار يا ناس - ام كلثوم",
  "683": "Mekhasmak Ya Alby - Farid Al-Atrash مخاصمك يا قلبى - فريد الأطرش",
  "684": "Men 6 Massaaan",
  "685": "Men Agl Ainak - Umm Kulthum من اجل عينيك - ام كلثوم",
  "686": "Men Bayn Lassami",
  "687": "Men Hakak Teatebny",
  "688": "Men Ho Yaanedna",
  "689": "Men Oul Khlessna",
  "690": "Men Radak Redo - Warda من رادك ريده - وردة",
  "691": "Men Shaa Aldaw",
  "692": "Men Sharadlil Ghazala",
  "693": "Men Soghro",
  "694": "Mesh Ketir Ala Alby - Sayed Mekawy مش كتير على قلبى - سيد مكاوي",
  "695": "Mestaneyak",
  "696": "Miin Ma Kenti",
  "697": "Mijana",
  "698": "Mili Ma Mal El Hawa",
  "699": "Min Elqahira",
  "700": "Min Kalbi",
  "701": "Min Sinin",
  "702": "Mish Ana El Massoul",
  "703": "Mishtaa Likr",
  "704": "Miskin Ou Hali Aadam (Original Mix)",
  "705":
    "Misr Nadetna- Mohamed Abd El Wahab مصر ناديتنا(وطنيات1) - محمد عبد الوهاب",
  "706": "Moch Biidi El Ochek",
  "707": "Mohamed Rasol Allah 1",
  "708": "Mohamed Rasol Allah 2",
  "709":
    "Mokadema Music El Nile Nagashy- Mohamed Abd El Wahab النيل نجاشي(وطنيات1) - محمد عبد الوهاب",
  "710": "Mostafa Ya Mostafa",
  "711": "Mouch Adra Ala Albi",
  "712": "Mouwashahat Ayouha Lsaki",
  "713":
    "Music Hedayet El Eead- Mohamed Abd El Wahab موسيقى هديةالعيد - محمد عبد الوهاب",
  "714": "Naaleh",
  "715": "Naam Ya Habibi Naam",
  "716": "Naddi Nassayem",
  "717":
    "Nagah Salam -  Magareh Wnbe Magareh  نجاح سلام - مجاريح و النبي مجاريح",
  "718":
    "Nagah Sallam -  Sobhan Alaam El Ghoyob   نجاح سلام - سبحان علام الغيوب",
  "719": "Nana",
  "720": "Nar El Ghera - Warda نار الغيرة - وردة",
  "721": "Naser - Mohamed Abd El Wahab ناصر ( وطنيات 5 ) - محمد عبد الوهاب",
  "722":
    "Nashead El Gehad- Mohamed Abd El Wahab نشيدالجهاد(وطنيات1) - محمد عبد الوهاب",
  "723": "Nashead El Kasam - Mohamed Abd El Wahab نشيد القسم - محمد عبد الوهاب",
  "724": "Nashead El Wady - Mohamed Abd El Wahab نشيد الوادي - محمد عبد الوهاب",
  "725": "Nazalty Souk Birasmali",
  "726": "Nazlet Tetnakal",
  "727":
    "Nebtady Menen ElHekaya(Short version) - Abdel Halim Hafez نبتدى منين الحكاية - عبد الحليم حافظ",
  "728": "Nessiou Wjouhon",
  "729": "Netkabel Sawa",
  "730": "O Tannenbaum",
  "731":
    "Oberait Ma Tekolsh Lehad - Farid Al-Atrash اوبريت - ما تقولش لحد - فريد الأطرش",
  "732": "Od Bina Ya Leyl",
  "733": "Oghneat El Dolab - Farid Al-Atrash اغنية الدولاب - فريد الأطرش",
  "734": "Oghneya Arabya - Mohamed Abd El Wahab أغنية عربية - محمد عبد الوهاب",
  "735": "Okbal Indoukom",
  "736": "Olla Lel Helwi",
  "737": "Om El Naby",
  "738": "Om El Remsh El Makhoul",
  "739": "Ouaa Tfouti Al Boustan",
  "740": "Oukba Landou Koum",
  "741": "Oulely Eah Aqolek - Farid Al-Atrash  قوليلى إيه اقولك - فريد الأطرش",
  "742": "Oulili Leysh Mbareh",
  "743": "Oumraha",
  "744": "Ouyoun El Halwin",
  "745": "Presentation",
  "746": "Qabel El Tawba",
  "747": "Qalqu Li Annak",
  "748":
    "Qareat El Fengan (Short version) - Abdel Halim Hafez قارئة الفنجان (نسخة قصيرة) - عبد الحليم حافظ",
  "749": "Qasri El Hawa",
  "750": "Qawli ya hlu",
  "751": "Qesat El Ams - Umm Kulthum قصة الامس - ام كلثوم",
  "752": "Qif Bel Kouchoua Wa Nadi Rabbak",
  "753": "Qissat Hob",
  "754": "Qul llilmaliha",
  "755": "Ragea Damerak",
  "756": "Rah Betchouf Ya Istaz",
  "757": "Rah Tewhacheni",
  "758": "Rahou El-Habayeb",
  "759": "Raks El Ghawazi",
  "760": "Raksat Addabke",
  "761": "Raksat Ashita",
  "762": "Raksat Tar El Harir",
  "763": "Raksat Yam Eddafayer",
  "764": "Ramayt Salam",
  "765": "Reddouha",
  "766": "Regaet Laialy Zamaan",
  "767": "Rekebna Al Hossan",
  "768": "Rjeena",
  "769": "Rjena W Rejou Al Habayeb",
  "770": "Robaeyat Salah Jaheen - Sayed Mekawy رباعيات صلاح جاهين - سيد مكاوي",
  "771": "Rohi Wa Rohek",
  "772": "Rohty Rohty",
  "773": "Rouhi W Rouhak",
  "774": "SAKEN FE HAY ELSYEDA",
  "775": "SALAS AYAM",
  "776": "SHOFTKHABETK YA SMARA",
  "777": "Saadeyee",
  "778": "Saal El Helw",
  "779": "Saalt Fy Hayena",
  "780": "Sabbahna Bifajr El Eid",
  "781": "Saet El Gad - Mohamed Abd El Wahab ساعة الجد - محمد عبد الوهاب",
  "782": "Saheb El Amar",
  "783": "Sahhar",
  "784": "Sahrana Idi Ala Khaddi",
  "785": "Saja Elleil (Original Mix)",
  "786": "Salam Alah Ya Taha",
  "787": "Salam Ali",
  "788": "Salam Leil Arees",
  "789": "Salamat",
  "790": "Salem Al Ahbab",
  "791": "Salla Allah Ala Mohamed Live Record",
  "792": "Salma",
  "793": "Salma Ya Salama",
  "794": "Salo Al Ahbab",
  "795": "Salo Koos El Tala - Umm Kulthum سلوا كؤوس الطلا - ام كلثوم",
  "796": "Salo Qalby - Umm Kulthum سلوا قلبى - ام كلثوم",
  "797": "Samra men qawm eisa",
  "798": "Samrai min kaoum issa",
  "799": "Sana an Sana",
  "800": "Sarli Saa Behki",
  "801":
    "Sawaed Men Belady - Mohamed Abd El Wahab سواعد من بلادي - محمد عبد الوهاب",
  "802": "Sawah",
  "803": "Sayartou Akbar",
  "804": "Shababna",
  "805": "Shagrat El Ahlam",
  "806": "Shahad",
  "807": "Shahat El Gharam",
  "808": "Shakra Wei Shaaraha Shakrawy",
  "809": "Shalahet Toob",
  "810": "Sharraf Habib El Qalb - Umm Kulthum شرف حبيب القلب - ام كلثوم",
  "811": "Shed El Hezam",
  "812": "Sheikh Masoud",
  "813": "Shewaky",
  "814": "Shwai Shwai",
  "815": "Shweky",
  "816": "Sibouni ya nasse (Live)",
  "817": "Sobhan Allah",
  "818": "Sodfa - Abdel Halim Hafez صدفه - عبد الحليم حافظ",
  "819": "Sodfe Eltaayna Al Darb",
  "820": "Sotak Nadany - Warda صوتك ناداني - وردة",
  "821":
    "Sout El Gamaher - Mohamed Abd El Wahab صوت الجماهير - محمد عبد الوهاب",
  "822": "Summary",
  "823": "Syriac 2",
  "824": "TESLM EDEN ELESHTRA",
  "825": "Ta Nessli Ya Ta Nessli",
  "826": "Taadabni",
  "827": "Taala Aoulak - Abdel Halim Hafez تعالى اقولك - عبد الحليم حافظ",
  "828": "Taala Salem - Farid Al-Atrash  تعالي سلم - فريد الأطرش",
  "829": "Tab en-Nasim al Alil",
  "830": "Tabaet El Khatem",
  "831": "Taht El Kanabel - Mohamed Abd El Wahab تحت القنابل - محمد عبد الوهاب",
  "832": "Tahyet El Alam - Mohamed Abd El Wahab تحية العلم - محمد عبد الوهاب",
  "833": "Takasim Oud",
  "834": "Tal Intizari (Original Mix)",
  "835": "Talaa min beit abouha",
  "836": "Talaffatet Zabyat Elwadi",
  "837": "Talat Daayeaa",
  "838": "Talieat min bayt abwahah",
  "839": "Tallet Am Tetdallae",
  "840": "Tallo Asseyadeh",
  "841": "Tallou Hbabna",
  "842": "Tamali Fi Qalbi Ya Habibi",
  "843": "Tawal Ghiyabak",
  "844":
    "Tebka beladena  Wardat ain el roummane  Keder el ankoud  Bekoulou bekutub el hawa (Medley)",
  "845": "Teeb Ttaab",
  "846": "Teegy",
  "847": "Tef Ya Dry",
  "848": "Tekhonoh - Abdel Halim Hafez تخونوه - عبد الحليم حافظ",
  "849": "Teleli Al Biki",
  "850": "Temli Fi Kalbi",
  "851": "Teqool Laa - Farid Al-Atrash  تقول لأ - فريد الأطرش",
  "852": "Ter Bina Ya Albi",
  "853": "Ter Bina Ya Kalbi",
  "854": "Tesal Aanni",
  "855":
    "Teslam Ya Ghaly - Mohamed Abd El Wahab تسلم يا غالى - محمد عبد الوهاب",
  "856": "Tihi Ala Arij Lwouroud",
  "857": "Tihi ala azaj alward",
  "858": "Tolli Ebalna",
  "859": "Toul Oumri (Original Mix)",
  "860": "Tyhi eali arj alwird",
  "861": "WADAA HAWAK",
  "862": "WANA MALY",
  "863": "Waadouni",
  "864": "Waady Elak",
  "865": "Waffar Marasilak",
  "866": "Wahdany - Farid Al-Atrash وحداني  - فريد الأطرش",
  "867": "Wahed Men Ashara Live",
  "868": "Wala Ya Wala",
  "869":
    "Walah We Arafna El Hob- Mohamed Abd El Wahab والله وعرفناالحب - محمد عبد الوهاب",
  "870": "Walaw",
  "871": "Wana Tayeh El Barriya",
  "872": "Warakou Al Assfar",
  "873": "Warda Men Damena - Farid Al-Atrash وردة من دمنا - فريد الأطرش",
  "874": "Wasel",
  "875": "Wassalouni We Rahou",
  "876": "Wassaou El Dara",
  "877": "Wassel",
  "878": "Wayak - Farid Al-Atrash وياك - فريد الأطرش",
  "879": "Wayna Weyn",
  "880": "Wehyat Eineky - Farid Al-Atrash وحياه عنيكي - فريد الأطرش",
  "881":
    "Wehyat Eineky Live Record - Farid Al-Atrash وحياه عنيكي تسجيل حفلة  - فريد الأطرش",
  "882": "Wehyatak Ya Habeby - Sayed Mekawy وحياتك يا حبيبى - سيد مكاوي",
  "883": "Wei Eshrah Laha",
  "884": "Wei Hoda - Habib Alby",
  "885": "Wei Leih Ya Mahboub",
  "886": "Wei Shwai Shwai",
  "887": "Weilak Yalli Teadeena",
  "888": "Weish Geibak Ya Ghazal",
  "889": "Weltakaina",
  "890": "Wesh Gebak Ya Ghazal",
  "891": "YA ABO ELEEYON ELSOD",
  "892": "YA AHL ELBALAD",
  "893": "YA BYENE WANA SHARE",
  "894": "YA HABIBE OLY AKHER GARHY EHA",
  "895": "YA SEET ELSOMR YA SAMRA",
  "896": "YA WEHDETY YANA",
  "897": "YAMH ELAMAR ALBAB",
  "898": "Ya Abou El Eyoun El Soud",
  "899": "Ya Abou El Tageya",
  "900": "Ya Aghia El Habayeb",
  "901": "Ya Ain Ad Alamar",
  "902": "Ya Alby",
  "903": "Ya Alby Khabby - Abdel Halim Hafez يا قلبى خبى - عبد الحليم حافظ",
  "904": "Ya Ashikat El Ward",
  "905": "Ya Atel Ya Maatoul",
  "906": "Ya Badaweya",
  "907": "Ya Bahgat El Roh",
  "908": "Ya Bahget El Eid - Umm Kulthum يا بهجة العيد - ام كلثوم",
  "909": "Ya Banat El Kala",
  "910": "Ya Bashier El Ouns - Umm Kulthum يا بشير الانس - ام كلثوم",
  "911": "Ya Belady - Mohamed Abd El Wahab يا بلادي - محمد عبد الوهاب",
  "912": "Ya Bent El Aam",
  "913": "Ya Bo Al Oyoun Helwin",
  "914": "Ya Bou Kheded Mnagrach",
  "915": "Ya Boul Kadada Beyda Pt 1",
  "916": "Ya Boul Kadada Beyda Pt 2",
  "917": "Ya Boul Marir El Mayel",
  "918": "Ya Boul Mihana",
  "919": "Ya Bouo Sena Dahb Louly",
  "920": "Ya Chiraaan Waraa Digla (Original Mix)",
  "921": "Ya Dayeiti",
  "922": "Ya Di Ennaim (Original Mix)",
  "923": "Ya Donya Hebena",
  "924": "Ya Einy La Tadmaai",
  "925": "Ya Eiyoun El Nargess",
  "926": "Ya Elahey - Mohamed Abd El Wahab يا إلهي - محمد عبد الوهاب",
  "927": "Ya Emm Al Foustan Al Nili",
  "928": "Ya Fayetni Be Hira",
  "929":
    "Ya Fayetny Wana Rouhy Maak - Umm Kulthum يا فايتنى وأنا روحى معاك - ام كلثوم",
  "930": "Ya Gamal",
  "931": "Ya Gameel - Farid Al-Atrash يا جميل  - فريد الأطرش",
  "932": "Ya Gamil Yali Hena",
  "933": "Ya Ghzayel Yamm Elheba",
  "934":
    "Ya Habaibi Ya Ahly - Farid Al-Atrash  يا حبايبى يا اهلي - فريد الأطرش",
  "935":
    "Ya Habaiby Ya Ghaiben - Farid Al-Atrash  ياحبايبى ياغايبين حفلة - فريد الأطرش",
  "936": "Ya Hadiya El Ais",
  "937": "Ya Hala",
  "938": "Ya Hala Bel Deif",
  "939": "Ya Hala Bel Mekahal",
  "940": "Ya Hala Wei Ya Marhab",
  "941": "Ya Halawet El Donya Live - Sayed Mekawy يا حلاوة الدنيا - سيد مكاوي",
  "942": "Ya Hallolli Ya Halawa",
  "943": "Ya Hazz Meen Yehwak",
  "944": "Ya Heleywa - Farid Al-Atrash يا حليوه - فريد الأطرش",
  "945": "Ya Helwe Ya Sabie",
  "946": "Ya Hilw Richak Nadah Li",
  "947": "Ya Hob",
  "948": "Ya Jamil Ya Li Hena",
  "949": "Ya Jar Erreda",
  "950": "Ya Kashef Alasrar",
  "951": "Ya Khedr El Akhedar",
  "952": "Ya Kheyam El Hana",
  "953": "Ya Khiyala",
  "954": "Ya Khofey Boaadoh - Farid Al-Atrash  ياخوفي بعاده - فريد الأطرش",
  "955": "Ya Laly",
  "956": "Ya Lawaati (Original Mix)",
  "957": "Ya Laylet el-id Insitina",
  "958": "Ya Leil Live Record - Warda ياليل تسجيل حفلة - وردة",
  "959": "Ya Ma Ya Ghali",
  "960":
    "Ya Malka El Alb Fe Edeik - Farid Al-Atrash يامالكه القلب في إيديك - فريد الأطرش",
  "961":
    "Ya Malkan Qalby(Short version) - Abdel Halim Hafez يا مالكا قلبي - عبد الحليم حافظ",
  "962": "Ya Mama",
  "963": "Ya Marek Al Tawahine",
  "964": "Ya Marhaba",
  "965":
    "Ya Masr Tam El Hana - Mohamed Abd El Wahab يامصرتم الهنا - محمد عبد الوهاب",
  "966": "Ya Medalaany",
  "967": "Ya Mehayer Qalbi Fe Houbak",
  "968": "Ya Mesaharny Live - Sayed Mekawy يا مسهرني - سيد مكاوي",
  "969": "Ya Miyet Halla",
  "970": "Ya Mounaya Ya Hawaya",
  "971": "Ya Moyharati Al Fok Al Jabal",
  "972":
    "Ya Nas La Mesh Keda Live - Sayed Mekawy يا ناس لأ مش كده تسجيل حفلة - سيد مكاوي",
  "973": "Ya Nass El Achraf",
  "974": "Ya Naïman Raqadat Goufounou",
  "975":
    "Ya Nesmat El Horeya- Mohamed Abd El Wahab يا نسمة الحرية - محمد عبد الوهاب",
  "976": "Ya Oraby Ya Rhala",
  "977": "Ya Oshak El Naby",
  "978": "Ya Qalby Kan Malak - Umm Kulthum يا قلبى كان مالك - ام كلثوم",
  "979": "Ya Qasr El Alaly",
  "980": "Ya Rayeh",
  "981": "Ya Reem",
  "982": "Ya Retny Taier - Farid Al-Atrash يا ريتني طير - فريد الأطرش",
  "983": "Ya Sabirine Sabrina",
  "984": "Ya Saher El Einein",
  "985": "Ya Salam",
  "986":
    "Ya Salam Ala Hopy We Hopak - Farid Al-Atrash  يا سلأم علي حبى وحبك - فريد الأطرش",
  "987": "Ya Salat El Zein",
  "988": "Ya Salat El Zein - Sayed Mekawy يا صلاة الزين - سيد مكاوي",
  "989": "Ya Salma",
  "990": "Ya Samrety Ya Helwa",
  "991": "Ya Sarek El Oubal",
  "992": "Ya Shady El Ahlam",
  "993": "Ya Shofeir",
  "994": "Ya Sidi",
  "995": "Ya Tair Ya Ayesh Aseer - Umm Kulthum يا طير يا عايش اسير - ام كلثوم",
  "996": "Ya Tara Ya Nisma (Original Mix)",
  "997": "Ya Teira Tiri",
  "998": "Ya Tiyargi",
  "999": "Ya Touyour",
  "1000": "Ya Ward Men Yashteryek",
  "1001": "Ya Ward Min (Original Mix)",
  "1002": "Ya Wardat El Hobb Essafi (From Al Warda Al Baidha) (Original Mix)",
  "1003": "Ya Wayhy Gaffa",
  "1004": "Ya Zabiat El Ban",
  "1005": "Ya Zabyata El Ban",
  "1006":
    "Ya Zahratan Fe Khaialy - Farid Al-Atrash يا زهره في خيالي - فريد الأطرش",
  "1007": "Ya Zarif Altol",
  "1008": "Ya bahjat arroh (Live)",
  "1009": "Ya dunia ya gharami",
  "1010": "Ya hadial osse (Live)",
  "1011": "Ya jararta al wadi",
  "1012": "Ya mal sham (Live)",
  "1013": "Ya shadil al-han (Live)",
  "1014": "Yabo El Gadaiel",
  "1015": "Yabo El Gedeila",
  "1016": "Yahady Al-Ys",
  "1017": "Yalla Bina Yalla",
  "1018": "Yalla Sawa - Farid Al-Atrash ياللا سوا - فريد الأطرش",
  "1019":
    "Yalla Sawa Live Record - Farid Al-Atrash  يا للا سوا تسجيل حفلة  - فريد الأطرش",
  "1020": "Yalla Tawakalna - Farid Al-Atrash ياللا توكلنا  - فريد الأطرش",
  "1021": "Yallah Tesobo Halkahwa",
  "1022": "Yalli Bebalek",
  "1023": "Yalli Chagak (From Al Warda Al Baidha) (Original Mix)",
  "1024": "Yalli Kan Yahqik Anini",
  "1025": "Yally Anta Baid",
  "1026": "Yally Gafak Elmanam - Umm Kulthum ياللى جفاك المنام - ام كلثوم",
  "1027": "Yally Raeet El Ohoud - Umm Kulthum يالى رعيت العهود - ام كلثوم",
  "1028": "Yally Teheb El Ward",
  "1029":
    "Yaly Hagart El Roh- Mohamed Abd El Wahab ياللي هجرت الروح - محمد عبد الوهاب",
  "1030": "Yam Alasawer",
  "1031": "Yam El Assawer",
  "1032": "Yam El Shama",
  "1033": "Yama Amar El Fora - Umm Kulthum ياما أمر الفراق - ام كلثوم",
  "1034": "Yama Baneit (Original Mix)",
  "1035": "Yama Nadeit - Umm Kulthum ياما ناديت - ام كلثوم",
  "1036": "Yamourrou oujban (Live)",
  "1037": "Yazal kawam (Live)",
  "1038": "Yemken Boukra",
  "1039": "Yeseid Messak",
  "1040": "Yessidli Sabahou",
  "1041": "Yesslam Lana Loubnan",
  "1042": "Yfed Beah El Anen - Farid Al-Atrash  يفيد بايةالانين - فريد الأطرش",
  "1043": "Yom Assafar",
  "1044": "Youm El Hana - Umm Kulthum يوم الهنا - ام كلثوم",
  "1045": "Youmien Wetalet",
  "1046": "Yssid Sabahak",
  "1047": "Zaboubih",
  "1048": "Zahr El Banafsaj",
  "1049": "Zaman Ya Hob - Farid Al-Atrash زمان يا حب حفلة - فريد الأطرش",
  "1050": "Zanoba",
  "1051": "Zarny Fe El Doha - Warda زارني في الضحي - وردة",
  "1052":
    "Zawed GeashAwtanak - Mohamed Abd El Wahab زود جيش أوطانك - محمد عبد الوهاب",
  "1053": "Zay Elhawa",
  "1054":
    "Zay Elhawa(Short version) - Abdel Halim Hafez زي الهوا - عبد الحليم حافظ",
  "1055": "Zekrayat",
  "1056": "Zekrayat - Umm Kulthum ذكريات - ام كلثوم",
  "1057": "Zina (Original Mix)",
  "1058": "Zorouny Kol Sana Mara",
  "1059": "ana mosh hena",
  "1060": "awel ma nseetak",
  "1061": "egra7ny egra7",
  "1062": "galak youm",
  "1063": "hasaharak",
  "1064": "kalam fe elhawa",
  "1065": "آه من الصبر",
  "1066": "آه يا خوفى",
  "1067": "أحبك عبد الحليم حافظ  Ahebak - Abdel Halim Hafez",
  "1068":
    "أحضان الحبايب عبد الحليم حافظ   Ahdan El Habayeb - Abdel Halim Hafez",
  "1069": "أحن اليك عبد الحليم حافظ  Ahaen Eleak - Abd El Halim Hafez",
  "1070": "أحن قلب الأم",
  "1071":
    "أدهم الشرقاوي عبد الحليم حافظ  Adham El Sharkawy - Abdel Halim Hafez",
  "1072":
    "أسمر يا اسمراني عبد الحليم حافظ  Asmar Ya Asmarany - Abdel Halim Hafez",
  "1073": "أشتاق أنا",
  "1074": "أعز الناس عبد الحليم حافظ  Aaz El Nas - Abdel Halim Hafez",
  "1075": "أغنية الفن",
  "1076": "ألبوم  - صباح يضم أغنية ( حموي يامشمش) نسخة HD",
  "1077": "أمة نعيمة",
  "1078": "أمه نعيمه",
  "1079": "أمي يا مصر عبد الحليم حافظ   Oumy Ya Masr - Abdel Halim Hafez",
  "1080": "إحنا الاتنين و العين في العين",
  "1081": "إدلع ياعريس",
  "1082": "إنت وانا اتنين سوا",
  "1083": "ابو امر غريب",
  "1084":
    "ابو عيون جريئة عبد الحليم حافظ  Abo Oyoun Gareea - Abdel Halim Hafez",
  "1085": "ابو عيون عسليه",
  "1086": "ابيض يا ورد",
  "1087": "اتمخطرى واتمايلى يا خيل",
  "1088": "اجمل سلام",
  "1089": "احبك شادية",
  "1090": "احبك قوى",
  "1091": "احتار خيالي عبد الحليم حافظ  Ehtar Khayaly - Abdel Halim Hafez",
  "1092": "احلي الكلام",
  "1093": "احن قلب",
  "1094": "احنا الشعب عبد الحليم حافظ  Ehna El Shaab - Abdel Halim Hafez",
  "1095": "احنا في جنينه",
  "1096": "احنا كنا فين عبد الحليم حافظ   Ehna Kona Fein - Abdel Halim Hafez",
  "1097": "اخر صوره",
  "1098": "ادلع يا رشيدي",
  "1099": "ادلع يا عريس",
  "1100": "ادي الحياه فرصه",
  "1101": "ادي زوبه زقه",
  "1102": "اروح لمين يا ربى",
  "1103": "اسال مجرب",
  "1104": "اسال مره عليا",
  "1105": "اسبقني يا قلبي عبد الحليم حافظ  Esbaani Ya Alby - Abdel Halim Hafez",
  "1106": "اسقنيها - اسمهان",
  "1107": "اسم الله",
  "1108": "اسمع البلبل - اسمهان",
  "1109": "اشهدى يا بيوت",
  "1110": "اضحك كركر",
  "1111": "اعز الولد",
  "1112": "اقولوا و لا لا",
  "1113": "اكرهه احبه",
  "1114": "الأصيل الذهبي عبد الحليم حافظ   Al Aseel - Abdel Halim Hafez",
  "1115": "البندقية عبد الحليم حافظ   Al Bondoqeya - Abdel Halim Hafez",
  "1116": "التوبة عبد الحليم حافظ   El Toba - Abdel Halim Hafez",
  "1117": "الحب الحقيقي",
  "1118": "الحب بهدلة",
  "1119": "الحب جميل",
  "1120": "الحب نسمة بتنور ليل الحيران",
  "1121": "الحلو حياتي عبد الحليم حافظ   El Helw Hayaty - Abd El Halim Hafez",
  "1122": "الحلوة عبد الحليم حافظ   El Helwa - Abdel Halim Hafez",
  "1123": "الحنه الحنه",
  "1124": "الدفاتر",
  "1125": "الدمع لما يفيض",
  "1126": "الدنيا غنوة",
  "1127": "الدنيا مالها",
  "1128": "الزفه",
  "1129": "السبت فات",
  "1130": "الشابة حتة سكره شادية",
  "1131": "الشاغل هو المشغول",
  "1132": "الشحرورة  صباح  -  اسطوانة",
  "1133": "الشحرورة صباح  -  اسطوانة",
  "1134": "الشحرورة صباح - اسطوانة",
  "1135": "الشحرورة صباح في مسرحية الشلال",
  "1136": "الشمس",
  "1137": "الشمس غابت انوارها (الغروب والشروق) - اسمهان",
  "1138": "الظلم حرام",
  "1139": "العين ما تعلاش",
  "1140": "الفن",
  "1141": "القلب معاك",
  "1142": "اللى يقدر على قلبى",
  "1143":
    "اللي انشغلت عليه عبد الحليم حافظ   Elly Enshaghalt Aleih - Abdel Halim Hafez",
  "1144": "اللي في قلبه حاجه يسألني",
  "1145": "الليالي عبد الحليم حافظ   El Layali - Abdel Halim Hafez",
  "1146": "الليلة تمت فرحتها",
  "1147": "المطرب الكبير محمد خير   وصلة طرب رابعة",
  "1148": "المطرب الكبير محمد خيري   الوصلة الثالثة عشر",
  "1149": "المطرب الكبير محمد خيري   الوصلة الثانية عشر",
  "1150": "المطرب الكبير محمد خيري   الوصلة الحادية عشر",
  "1151": "المطرب الكبير محمد خيري   الوصلة الرابعة عشر",
  "1152": "المطرب الكبير محمد خيري   الوصلة العاشرة",
  "1153": "المطرب الكبير محمد خيري   وصلة طرب أولى",
  "1154": "المطرب الكبير محمد خيري   وصلة طرب تاسعة",
  "1155": "المطرب الكبير محمد خيري   وصلة طرب ثامنة",
  "1156": "المطرب الكبير محمد خيري   وصلة طرب خامسة",
  "1157": "المطرب الكبير محمد خيري   وصلة طرب سابعة",
  "1158": "المطرب الكبير محمد خيري   وصلة طرب سادسة",
  "1159": "المطرب الكبير محمد خيري وصلة طرب ثالثة",
  "1160": "المطربة الكبيرة سعاد محمد   اجمل سلام  ( Souad Mohammad )",
  "1161": "المطربة الكبيرة سعاد محمد   مظلومة يا ناس  ( Souad Mohamed )",
  "1162": "المطربة الكبيرة سعاد محمد   وحشتني  ( Souad Mohamed )",
  "1163": "المطربة الكبيرة سعاد محمد   يا بخت المرتاحين  ( Souad Mohamed )",
  "1164":
    "المطربة الكبيرة سعاد محمد تغني لأم كلثوم  هو صحيح الهوى غلاب  ( Souad Mohamed )",
  "1165":
    "المطربة الكبيرة سعاد محمد تغني لكوكب الشرق أم كلثوم  أنساك  ( Souad Mohamed )",
  "1166":
    "المطربة الكبيرة سعاد محمد تغني لكوكب الشرق أم كلثوم  الأطلال  ( Souad Mohamed )",
  "1167":
    "المطربة الكبيرة سعاد محمد تغني للشيخ سيد درويش  انا هويت  ( Souad Mohamed )",
  "1168":
    "المطربة الكبيرة سعاد محمد في رائعة الموسيقار فريد الأطرش  بقى عايز تنساني  ( Souad Mohamed )",
  "1169": "الناس المغرمين",
  "1170": "الهوي هوايا عبد الحليم حافظ   El Hawa Hawaya - Abdel Halim Hafez",
  "1171": "الو الو احنا هنا",
  "1172": "الورد و الشوك",
  "1173": "الوشوشه",
  "1174": "الوطن عبد الحليم حافظ   El Watan El Akbar - Abdel Halim Hafez",
  "1175": "ام العيون السود - ناظم الغزالي HD",
  "1176": "امتى حتعرف - اسمهان",
  "1177": "امتى يهون كل دا",
  "1178": "ان الاوان",
  "1179": "ان راح منك يا عين",
  "1180": "ان فات عليك الهوي",
  "1181": "انا اترجاه",
  "1182": "انا اللي استاهل - اسمهان",
  "1183": "انا بنت حلوه",
  "1184": "انا خايفه",
  "1185": "انا طير جريح",
  "1186": "انا عندي مشكله",
  "1187": "انا فين",
  "1188": "انا قلبى خالى",
  "1189":
    "انا لك على طول عبد الحليم حافظ   Ana Lak Ala Toul - Abdel Halim Hafez",
  "1190": "انا مخاصماك",
  "1191": "انا من تراب عبد الحليم حافظ   Ana Men Torab - Abdel Halim Hafez",
  "1192": "انا هويت",
  "1193": "انا وانت عصفورين",
  "1194": "انا وردة",
  "1195": "انت اول حب",
  "1196": "انت هنا وانا هنا",
  "1197": "انعودت عليك",
  "1198": "اه يا اسمرانى اللون  شـاروخـان  الملك خــان ",
  "1199": "اه يا جمال العيون",
  "1200": "اه يا لاموني",
  "1201": "اه يا نور عينيه",
  "1202": "اه ياليل",
  "1203": "اهواك عبد الحليم حافظ   Ahwak - Abdel Halim Hafez",
  "1204": "اهوى - اسمهان",
  "1205": "اوبريت انتصارالشباب - اسمهان",
  "1206": "اوعى يكون فات الاوان",
  "1207": "اول لقانا",
  "1208": "اول مرة عبد الحليم حافظ   Awel Mara - Abdel Halim Hafez",
  "1209":
    "اي دمعة حزن لا عبد الحليم حافظ   Ay Damaet Hozn La - Abdel Halim Hafez",
  "1210": "ايدي في ايدك - اسمهان",
  "1211": "ايرما لا دوس",
  "1212": "اين الليالي - اسمهان",
  "1213": "ايه جرالك",
  "1214": "ايه ذنبى ايه عبد الحليم حافظ   Eh Zanby Eh - Abdel Halim Hafez",
  "1215": "ايها النائم - اسمهان",
  "1216": "اِحنا الحبايب و اِحنا القرايب - سميرة توفيق",
  "1217": "بأمر الحب عبد الحليم حافظ   Be Amr El Hob - Abdel Halim Hafez",
  "1218": "بتقول ايه عبد الحليم حافظ   Btqwl iyh - Abdel Halim Hafez",
  "1219": "بتكلموني ليه",
  "1220": "بتلومني ليه عبد الحليم حافظ   Betlomouny Leih - Abdel Halim Hafez",
  "1221": "بحب اتنين سوا",
  "1222": "بحلم بيك عبد الحليم حافظ   Bahlam Beek - Abdel Halim Hafez",
  "1223": "برجالاتك",
  "1224": "برد الطقس",
  "1225": "بسبس نو",
  "1226": "بست القمر",
  "1227":
    "بستان الاشتراكية عبد الحليم حافظ   Bostan El Eshtrakeya - Abdel Halim Hafez",
  "1228": "بعد غيبة",
  "1229": "بعدت ليه ياحبيبى",
  "1230": "بكرة وبعده عبد الحليم حافظ   Bokra We Baado - Abdel Halim Hafez",
  "1231": "بكير بعدك يا صغيره",
  "1232": "بلادي عبد الحليم حافظ   Belady - Abdel Halim Hafez",
  "1233": "بلاش عتاب عبد الحليم حافظ   Balash Eletab - Abd El Halim Hafez",
  "1234": "بنت النيل - اسمهان",
  "1235": "بنتي",
  "1236": "بياع الهوى",
  "1237": "بياع الهوي",
  "1238": "بيع قلبك عبد الحليم حافظ   Bea Albak - Abdel Halim Hafez",
  "1239":
    "بيني وبينك ايه عبد الحليم حافظ   Beiny We Beinak Eh - Abdel Halim Hafez",
  "1240": "بيني وبينك عبد الحليم حافظ   Beiny We Beinak Eh - Abdel Halim Hafez",
  "1241": "تحت البلكونه",
  "1242": "تسأل عني بأول يوم - نصري شمس الدين",
  "1243": "تسال عنى",
  "1244": "تلات شهور",
  "1245": "توبة عبد الحليم حافظ  Toba - Abd El Halim Hafez",
  "1246": "جانا الهوي عبد الحليم حافظ   Gana El Hawa - Abdel Halim Hafez",
  "1247": "جايين من بلاد الغربه",
  "1248": "جبار عبد الحليم حافظ   Gabar - Abdel Halim Hafez",
  "1249": "جرا ايه",
  "1250": "جواب عبد الحليم حافظ   Gawab - Abd El Halim Hafez",
  "1251": "ح اعيش",
  "1252": "حاول تفتكرني عبد الحليم حافظ   Hawel Teftekerny - Abdel Halim Hafez",
  "1253": "حب و اتحب",
  "1254": "حبك نار عبد الحليم حافظ   Hobak Nar - Abd El Halim Hafez",
  "1255": "حبك ياعبده",
  "1256": "حبه حبه",
  "1257": "حبيب حياتي عبد الحليم حافظ   Habeeb Hayaty - Abdel Halim Hafez",
  "1258": "حبيبه",
  "1259": "حبيبها عبد الحليم حافظ   Habibaha - Abd El Halim Hafez",
  "1260": "حبيبى قاعد وسطكم",
  "1261": "حبيبي",
  "1262": "حبيتك و بحبك",
  "1263": "حبينا بعضنا شادية",
  "1264": "حرام يا نار عبد الحليم حافظ   Haram Ya Nar - Abdel Halim Hafez",
  "1265": "حقك عليا متزعلش",
  "1266": "حكاية شعب عبد الحليم حافظ   Hekayet Shaab - Abdel Halim Hafez",
  "1267": "حكايتي كانت",
  "1268": "حلو وكذاب عبد الحليم حافظ   Helw We Kadab - Abdel Halim Hafez",
  "1269": "حماتى يا نينة",
  "1270": "حنيت لك",
  "1271": "حيران فى دنيا الخيال",
  "1272":
    "خايف مرة أحب عبد الحليم حافظ   Khayef Marra Aheb - Abdel Halim Hafez",
  "1273": "خد بالك",
  "1274": "خد يا حبيبي",
  "1275": "خسارة عبد الحليم حافظ   Khosara - Abdel Halim Hafez",
  "1276": "خلاص مسافر",
  "1277":
    "خلي السلاح صاحي عبد الحليم حافظ   Khally El Selah Sahy - Abdel Halim Hafez",
  "1278": "خليك سبور يا قلبى",
  "1279": "خمسة خميسة",
  "1280": "خمسه في سته",
  "1281": "دبكه عالدوره",
  "1282": "دبله الخطوبه",
  "1283": "دخلت مرة في جنينة - اسمهان",
  "1284": "دق الكف  Sabah a Paris live",
  "1285": "دقه قلبي",
  "1286": "دقوا الأحباب",
  "1287": "دقوا المزاهر",
  "1288": "دلوقتي حالان",
  "1289": "دور عليه تلقاه",
  "1290": "دور يا ماتور",
  "1291": "دوس ع الدنيا",
  "1292": "دى مواعيد",
  "1293": "ديالوج رايح تفوتنى",
  "1294": "ديالوج يا قلب ليه",
  "1295": "ذات ليلة عبد الحليم حافظ   That Layla - Abdel Halim Hafez",
  "1296": "ذكريات عبد الحليم حافظ   Thekrayat - Abdel Halim Hafez",
  "1297": "راح الحب",
  "1298": "راح الشهر و هل الشهر",
  "1299": "راح عبد الحليم حافظ   Rah - Abd El Halim Hafez",
  "1300": "رباعيات الخيام",
  "1301": "ربما عبد الحليم حافظ   Robbama - Abdel Halim Hafez",
  "1302": "رجعت لك ياحبيبي - اسمهان",
  "1303": "رحله العمر",
  "1304":
    "رسالة من تحت الماء عبد الحليم حافظ   Resala Men Taht El Maa - Abdel Halim Hafez",
  "1305": "رقصتك بالعيد",
  "1306": "رنة قبقابي شادية",
  "1307": "روحتى فين يا صغيرة",
  "1308": "روحي حياتي عبد الحليم حافظ   Rouhy Hayaty - Abdel Halim Hafez",
  "1309": "ريداك ونبى ريداك",
  "1310": "زعلت حليمه",
  "1311": "زغروطة و سمعتها",
  "1312": "زي الهوي عبد الحليم حافظ   Zay El Hawa - Abdel Halim Hafez",
  "1313": "سألت عليه قالو مسافر",
  "1314": "ساعه ما باشوفك جنبي (حفله)",
  "1315": "ساكن قصادي",
  "1316": "ست العرايس",
  "1317": "سعاد محمد  - حرام",
  "1318": "سعاد محمد - (دور) انت فاهم قلبي تاني يرق لك",
  "1319": "سعاد محمد - (دور) ماهو انت اللي جايبه لروحك  مسبوقا بموشح بنت كرم",
  "1320": "سعاد محمد - (قصيدة) أنا قد نسيتك",
  "1321": "سعاد محمد - (قصيدة) أتحبني حقا؟",
  "1322": "سعاد محمد - (قصيدة) أنا وحدي",
  "1323": "سعاد محمد - (قصيدة) عُد لنا",
  "1324": "سعاد محمد - (قصيدة) ما هكذا أسرفت يا أسمر",
  "1325": "سعاد محمد - (قصيدة) هكذا ننتهي",
  "1326": "سعاد محمد - (قصيدة) وداع",
  "1327": "سعاد محمد - أنغام الماضي (امانة عليك) - ستوديو 1972",
  "1328": "سعاد محمد - أوعدك - تسجيل في دمشق",
  "1329": "سعاد محمد - إذا ما الصبح نادانا",
  "1330": "سعاد محمد - العمر ليلة",
  "1331": "سعاد محمد - العمر ليلة (أحبك واتحرم منك) - سينما أوبرا 1960",
  "1332": "سعاد محمد - الله على الحب",
  "1333": "سعاد محمد - امتى الهوى ينصف حبيبين",
  "1334": "سعاد محمد - امتى الهوى ينصف حبيبين؟ - تسجيل إذاعي 1957",
  "1335": "سعاد محمد - انساك  من ارشيف تلفزيون لبنان ( Souad Mohamed )",
  "1336": "سعاد محمد - اهجر واقسى وانسى اللي كان",
  "1337": "سعاد محمد - أجمل سلام",
  "1338": "سعاد محمد - أنا ناسية أهلي وناسي",
  "1339": "سعاد محمد - إذا ما الصبح نادانا",
  "1340": "سعاد محمد - إلهي رب العالمين - حفل دمشق 1960",
  "1341": "سعاد محمد - بقى عايز تنساني  من حفلاتها المصورة ( Souad Mohamad )",
  "1342": "سعاد محمد - بقى عايز تنساني  من حفلاتها المصوّرة ( Souad Mohamed )",
  "1343": "سعاد محمد - تحت الجفون ياما - تسجيل إذاعي",
  "1344": "سعاد محمد - تنهيدة",
  "1345": "سعاد محمد - زي الطير يا حبيبي بتهجر",
  "1346": "سعاد محمد - غريبة والزمن قاسي",
  "1347": "سعاد محمد - فتح الهوا الشباك  مظلومة - حفل الباخرة سودان 1954",
  "1348": "سعاد محمد - قصيدة أحب الله ( Souad Mohamad )",
  "1349":
    "سعاد محمد - قصيدة إنتظار للسنباطي  حفلة قرطاج الكاملة  ( Souad Mohamad )",
  "1350": "سعاد محمد - قصيدة القدس (قومي إلى الصلاة) - حفل 1969",
  "1351": "سعاد محمد - قصيدة انتظار (مقطع) - حفل مصور",
  "1352": "سعاد محمد - قصيدة انتظار - حفل نادر",
  "1353": "سعاد محمد - قصيدة حبيبة السماء (قومي إلى الصلاة) - حفل 1969",
  "1354": "سعاد محمد - لبيك رب السماء",
  "1355": "سعاد محمد - لبّيك رب السماء",
  "1356": "سعاد محمد - ماحناش ناقصين يا قلبي",
  "1357": "سعاد محمد - ماهو انت اللي جايبه لروحك ( Souad Mohamad )",
  "1358": "سعاد محمد - محتارة يا ناس",
  "1359": "سعاد محمد - مختارات من الزمن الجميل ( Souad Mohammed )",
  "1360": "سعاد محمد - مظلومة يا ناس - تسجيل اسطوانة",
  "1361": "سعاد محمد - مظلومة يا ناس - حفل  يناير 1964",
  "1362": "سعاد محمد - من غير حب (قاسيت) - تسجيل ستوديو",
  "1363": "سعاد محمد - من غير حب (قاسيت) - حفل حلب 1960",
  "1364": "سعاد محمد - من غير حب - حفل الإسماعيلية 1963",
  "1365":
    "سعاد محمد - من غيرحب  قاسيت  من حفلات على شط النيل ( Souad Mohamed )",
  "1366": "سعاد محمد - هو صحيح الهوى غلاب - الكويت",
  "1367": "سعاد محمد - يا حبيبي يا رسول الله 1952",
  "1368": "سعاد محمد - يا نازلين البحر - تسجيل تلفزيوني",
  "1369": "سعاد محمد - يا نديمي آه من سحر النوى",
  "1370": "سعاد محمد - يطول ليلي  - حفل التلفزيون 1961",
  "1371":
    "سعاد محمد وأحمد صدقي - (دور) ماهو انت اللي جايبه على العود + حديث عن زكريا أحمد",
  "1372": "سعديه",
  "1373": "سعيدة",
  "1374": "سكه العاشقين",
  "1375": "سكيتش من مسرحية القلعة",
  "1376": "سلام وكلام",
  "1377": "سلم على",
  "1378": "سلملي عليه",
  "1379": "سلوى القطريب - خدني معك",
  "1380": "سنه اولي حب",
  "1381": "سنه حلوه",
  "1382": "سهران يا قمر",
  "1383": "سواح عبد الحليم حافظ   Sawwah - Abdel Halim Hafez",
  "1384": "سوق على مهلك",
  "1385": "سي السيد",
  "1386": "شباكنا ستايره حرير شادية",
  "1387": "شبك حبيبي شادية",
  "1388": "شبكت قلبي",
  "1389": "شغلوني عبد الحليم حافظ   Shaghalouny - Abdel Halim Hafez",
  "1390": "شفتها و جنيت",
  "1391": "شهر العسل",
  "1392": "شوفت منام",
  "1393": "شيئ غريب",
  "1394": "صابرين",
  "1395": "صافيني مرة عبد الحليم حافظ   Safeeny Marra - Abdel Halim Hafez",
  "1396": "صباح",
  "1397": "صباح   -   ساعات  ساعات",
  "1398": "صباح   -   كاسيت  -  مفيش حلاوة من غير نار",
  "1399": "صباح  -  أنا عاوزه اتحب  -  كاسيت",
  "1400": "صباح  -  اه يامعلم",
  "1401": "صباح  -  بحبك لكن خايفة",
  "1402": "صباح  -  بدي حبو بدي 1990",
  "1403": "صباح  -  ترللي",
  "1404": "صباح  -  حلوة  لبنان",
  "1405": "صباح  -  دق الكف",
  "1406": "صباح  -  راجعة على ضيعتنا",
  "1407": "صباح  -  ربّما",
  "1408": "صباح  -  رح أغسل أرضك بدموعي 🇱🇧🇱🇧",
  "1409": "صباح  -  رقصني دخلك ياحبيبي",
  "1410": "صباح  -  روحي ياصيفية",
  "1411": "صباح  -  شرفي وارضي",
  "1412": "صباح  -  شو اسمك",
  "1413": "صباح  -  طيب طيب",
  "1414": "صباح  -  عاشقة وغلبانة",
  "1415": "صباح  -  عالدبكة قوموا",
  "1416": "صباح  -  عالندا",
  "1417": "صباح  -  عني يامنجيرة",
  "1418": "صباح  -  عيني ياعيني",
  "1419": "صباح  -  قايمة ضب تيابي",
  "1420": "صباح  -  قوللى يا قلبي",
  "1421": "صباح  -  كاسيت  -  ياحبيب القلب 1987",
  "1422": "صباح  -  كاسيت  -  يعجبني قوي  1984",
  "1423": "صباح  -  لاتعاندني بتتعب",
  "1424": "صباح  -  ماعد بدنا حبايب",
  "1425": "صباح  -  مافي نوم بعد اليوم",
  "1426": "صباح  -  مجدك باقي 🇱🇧🇱🇧",
  "1427": "صباح  -  مرحبا يا حبايب",
  "1428": "صباح  -  مقدر من الله",
  "1429": "صباح  -  ممنوع الغلط",
  "1430": "صباح  -  وادي شمسين",
  "1431": "صباح  -  ياجبال بلادي 🇱🇧🇱🇧",
  "1432": "صباح  -  ياخدو عيوني",
  "1433": "صباح  -  ياليلى",
  "1434": "صباح  -  يانا يانا",
  "1435": "صباح  -  يسلم لنا لبنان 🇱🇧🇱🇧",
  "1436": "صباح  -  يلا نعيش الحياة",
  "1437": "صباح  - جنينة حبيبي",
  "1438": "صباح  - عاشقة وطني الغالي",
  "1439": "صباح  أنا كده دلوعة  حفل الشام 1985",
  "1440": "صباح  حسّونة حفل الشام 1985",
  "1441": "صباح  رجعنا - قلعة كبيرة",
  "1442": "صباح  رقصني هيك  حفل سوريا 1985",
  "1443": "صباح  زقفة ياشباب",
  "1444": "صباح  شو اسمك  حفل سوريا 1985",
  "1445": "صباح  لأَ لأَ  Sabah la2a",
  "1446": "صباح ( اسطوانة ) يم عيون القتالة  -  جينا الدار",
  "1447": "صباح -  أغاني ساعة وغنية 1979",
  "1448": "صباح - (  دمه خفيف - بيني وبينك ثار)",
  "1449": "صباح - (عالليلكي - الله معك يا زنبقة )",
  "1450": "صباح - آلو بيروت",
  "1451": "صباح - أسطوانة ( بياع التفاح)",
  "1452": "صباح - أسطوانة ( جوزي مابيلفي عالبيت)",
  "1453": "صباح - أغاني مسرحية حلوى كتير",
  "1454": "صباح - ألبوم يضم أغنيتين ( بكرا بكرا لاقينا - آخر مرة بحب)",
  "1455": "صباح - ألبوم يضم أغنيتين أجنبيتين (Haley Dabki - Sola)",
  "1456": "صباح - ألوف ألوف",
  "1457": "صباح - أنا هنا يابن الحلال",
  "1458": "صباح - إسطوانة تحمل أغاني  فلكلور شعبي",
  "1459": "صباح - ابو الزلف Mawal",
  "1460": "صباح - اتغندري يامغندرة",
  "1461": "صباح - اسطوانة ( آخد قلبي سكارسا )",
  "1462": "صباح - اسطوانة ( انزل عالبندر )",
  "1463": "صباح - اسطوانة - ( بلوطاتك بلوطة - ياجوز التنتين )",
  "1464": "صباح - اسطوانة - ( طعميتك سكر - شفت ألوف )",
  "1465": "صباح - اسطوانة - ( على عين الحب )",
  "1466": "صباح - اسطوانة - ( ياراجل ياطيب - قمورتي الحلوة )",
  "1467": "صباح - اسطوانة - (درجي دوسا دوبارا - شوبدي أعمل إلي )",
  "1468": "صباح - اسطوانة - زي العسل",
  "1469": "صباح - اسطوانة - قالولي الحب بينباع",
  "1470": "صباح - اسطوانة تحمل أغنيتن ( طق ودوب - وز عينك )",
  "1471": "صباح - اسطوانة تحمل أغنيتين ( قلبي عم يدق - عالغندورة )",
  "1472": "صباح - البوم يتضمن أغنيتين من مسرحية ( حلوى كتير) نسخة HD",
  "1473": "صباح - الدنيا احلوت",
  "1474": "صباح - اهلا بهالطلّة",
  "1475": "صباح - ايام اللولو",
  "1476": "صباح - تعلى وتتعمر",
  "1477": "صباح - جاري أنا جاري",
  "1478": "صباح - جنينة حبيبي",
  "1479": "صباح - جوزي مابيلفي عالبيت",
  "1480": "صباح - حوار ياشباب",
  "1481": "صباح - دخل عيونك",
  "1482": "صباح - راس الطلعة",
  "1483": "صباح - زي القمر",
  "1484": "صباح - ساعات  Sabah Saat",
  "1485": "صباح - شو هيدا الحُب",
  "1486": "صباح - عالضيعة",
  "1487": "صباح - عالعصفورية",
  "1488": "صباح - عالمنديل",
  "1489": "صباح - عبدو عبيد",
  "1490": "صباح - عدى عليا وسلم",
  "1491": "صباح - عطشانة ياصبايا",
  "1492": "صباح - عني يا منجيرة",
  "1493": "صباح - عين وقلب",
  "1494": "صباح - غلطان بالنمرة",
  "1495": "صباح - قلبي عم يدق",
  "1496": "صباح - لمجوز الله يزيده",
  "1497": "صباح - معقوله",
  "1498": "صباح - مفيش غيرك",
  "1499": "صباح - منورين Sabah  menawareen",
  "1500": "صباح - يا خيل بالليل اشتدي",
  "1501": "صباح - ياحلو",
  "1502": "صباح - ياعزيز عيني",
  "1503": "صباح - يانا يانا",
  "1504": "صباح البوم - (ياربي تشتي عرسان)",
  "1505": "صباح البوم - ياهلابو  ياهلاب",
  "1506": "صدفة عبد الحليم حافظ   Sodfa - Abdel Halim Hafez",
  "1507": "صورة عبد الحليم حافظ   Soura - Abdel Halim Hafez",
  "1508": "صيد العصارى",
  "1509": "ضحك ولعب عبد الحليم حافظ   Dehk We Leab - Abdel Halim Hafez",
  "1510": "ضحك ولعب وجد وحب عبد الحليم حافظ   Dehk We Leab - Abdel Halim Hafez",
  "1511": "ضي القناديل عبد الحليم حافظ   Day El Kanadil - Abdel Halim Hafez",
  "1512": "طاب و استوي",
  "1513": "طالعة السلالم",
  "1514": "طلوا طلوا الصياده",
  "1515": "طول عمرى أحبك - نجاة  Tol Omry Ahebak - Nagat",
  "1516": "طيارة فوق",
  "1517": "طياره",
  "1518": "ظلموه عبد الحليم حافظ   Zalamoh - Abdel Halim Hafez",
  "1519": "عاش اللي قال عبد الحليم حافظ   Ash Elly Al - Abdel Halim Hafez",
  "1520": "عالعالى الدار",
  "1521": "عالعين",
  "1522": "عالهوب الهوب",
  "1523": "عالي الود",
  "1524": "عاهدني ياقلبي - اسمهان",
  "1525": "عدولى يا جماعه",
  "1526": "عدي النهار عبد الحليم حافظ   Euday Alnahar - Abdel Halim Hafez",
  "1527": "عذابي في هواك - اسمهان (بصوت برلنتي حسن)",
  "1528": "عشرين",
  "1529":
    "عقبالك يوم ميلادك عبد الحليم حافظ   Okbalk Yom Meladak - Abdel Halim Hafez",
  "1530": "علشانك يا قمر عبد الحليم حافظ   Ashanak Ya Amar - Abdel Halim Hafez",
  "1531": "علهوب الهوب",
  "1532": "على اخر سرعه",
  "1533": "على دلعونه",
  "1534": "على عين الميه يا سمرا",
  "1535": "على قد الشوق عبد الحليم حافظ   Ala Ad El Shouq - Abdel Halim Hafez",
  "1536":
    "على قد الشوق عبد الحليم حافظ   Ala Kad El Shook - Abd El Halim Hafez",
  "1537": "على وسطك لفى منديلك",
  "1538": "علي شلهوب - مجاريح يا أهل الهوى (ستوديو - جودة عالية) 1984",
  "1539": "عليك صلاة الله - اسمهان",
  "1540": "عم تغزل",
  "1541": "عيب يامديحه",
  "1542":
    "عيني أضناها السهر عبد الحليم حافظ   Ainy Danaha Al Sahar - Abdel Halim Hafez",
  "1543": "عيونك بحر أزرق ـ نجيب السراج",
  "1544": "غاب عنى ليه",
  "1545": "غابت مراسيلاك",
  "1546": "غنيلي شوي شوي",
  "1547": "فات يوم الاتنين",
  "1548": "فاتت جنبنا عبد الحليم حافظ   Fatet Ganbena - Abdel Halim Hafez",
  "1549": "فارس احلامي شادية",
  "1550": "فاكراك",
  "1551": "فايت عينييه",
  "1552": "فرح فؤادى يوم رؤياك",
  "1553": "فرق مابينا ليه الزمان - اسمهان",
  "1554": "فريد الأطرش سعاد محمد فايدة كامل فجر - يا مرحبا بك يا جمال",
  "1555": "فوت يا حبيبي",
  "1556": "في الصيف",
  "1557": "في ظل فاروق رفعنا العلم",
  "1558":
    "في يوم في شهر في سنة عبد الحليم حافظ   Fe Youm Fe Shahr - AbdEl Halim Hafez",
  "1559": "في يوم ما اشوفك - اسمهان",
  "1560":
    "في يوم من الأيام عبد الحليم حافظ   Fe Yom Min ElAyam - Abd El Halim Hafez",
  "1561": "فيروز - أحب دمشق  Fairouz - Uhib dimashq",
  "1562": "فيروز - إيه في أمل  Fairouz - Eh fi amal",
  "1563": "فيروز - احكيلي عن بلدي  Fairouz - Ahkili an baladi",
  "1564": "فيروز - الأرض لكم  Fairouz - Al ardu lakum",
  "1565": "فيروز - البنت الشلبية  Fairouz - bint el chalabiya",
  "1566": "فيروز - الله كبير  Fairouz - Allah kbir",
  "1567": "فيروز - بكتب اساميهن  Fairouz - Bektob asamihn",
  "1568": "فيروز - تل الزعتر  Fairouz - Tal el zaatar",
  "1569": "فيروز - ديار بكر  Fairouz - Deyar baker",
  "1570": "فيروز - سائليني يا شآم  Fairouz - Saileni ya shaam",
  "1571": "فيروز - شام يا ذا السيف  Fairouz - Shamu ya dha sayef",
  "1572": "فيروز - قال قايل  Fairouz - Al ayel",
  "1573": "فيروز - قرأت مجدك  Fairouz - Qaratu majdaki",
  "1574": "فيروز - قصة صغيرة كتِير  Fairouz - Ossa zghiri ktir",
  "1575": "فيروز - كبيرة المزحة هاي  Fairouz - Kbiril mazha hay",
  "1576": "فيروز - كل ما الحكي  Fairouz - Kel mal haki",
  "1577": "فيروز - ما شاورت حالي  Fairouz - Ma shawart hali",
  "1578": "فيروز - نسمت  Fairouz - Nassamat",
  "1579": "فيروز - يا شام عاد الصيف  Fairouz - Ya shamo aada al ssaif",
  "1580":
    "قارئة الفنجان عبد الحليم حافظ   Qareat El Fengan - Abdel Halim Hafez",
  "1581": "قدمنا له الحب شادية",
  "1582": "قصيدة بيت الحبيبة للمطرب الكبير نجيب السراج",
  "1583": "قلبى دليلى",
  "1584": "قللي بحبك",
  "1585": "قلولوا يا ناس الظلم حرام",
  "1586": "قول لي يا زمان - سميرة توفيق",
  "1587": "قولوا لعين الشمس",
  "1588": "قولولو الحقيقة عبد الحليم حافظ   Ouloul - Abd El Halim Hafez",
  "1589": "قولي حاجة عبد الحليم حافظ   Kolly Haga - Abd El Halim Hafez",
  "1590": "كأنك معايا",
  "1591": "كارم محمود - عينى بترف",
  "1592": "كاس الهنا",
  "1593": "كامل الأوصاف عبد الحليم حافظ   Kamel El Awsaf - Abd El Halim Hafez",
  "1594":
    "كان في زمان قلبين عبد الحليم حافظ   Kan Fi Zaman Albein - Abdel Halim Hafez",
  "1595": "كان لي أمل - اسمهان",
  "1596": "كان مالي انا",
  "1597": "كحيل  العين  -  صباح",
  "1598":
    "كفاية نورك عليا عبد الحليم حافظ   Kefaya Nourak - Abd El Halim Hafez",
  "1599": "كل دقة فى قلبى",
  "1600": "كلك حنيه",
  "1601": "كلمة يا نور العيون - اسمهان",
  "1602": "كلمنى يا قمر",
  "1603": "كنت الاماني - اسمهان",
  "1604": "كنت فين عبد الحليم حافظ   Kont Fein - Abd El Halim Hafez",
  "1605": "كيف حالهن",
  "1606": "لا تشتكى",
  "1607": "لالا له لالا",
  "1608":
    "لايق عليك الخال عبد الحليم حافظ   Layek Aleik El Khal - Abdel Halim Hafez",
  "1609": "لحن الوفاء عبد الحليم حافظ   Lahn El Wafaa - Abdel Halim Hafez",
  "1610": "لست أدري عبد الحليم حافظ   Last Adry - Abdel Halim Hafez",
  "1611": "لست قلبي عبد الحليم حافظ   Last Kalby - Abd El Halim Hafez",
  "1612": "لقاء عبد الحليم حافظ   Leqa - Abdel Halim Hafez",
  "1613": "لو القلوب",
  "1614": "لو تفرشلي الأرض حنة",
  "1615":
    "لو كنت يوم أنساك عبد الحليم حافظ   Law Kont Yom Ansak - Abdel Halim Hafez",
  "1616": "ليالي الانس - اسمهان",
  "1617": "ليالي العمر",
  "1618": "ليت للبراقِ عيناً - اسمهان",
  "1619": "ليلة من العمر",
  "1620": "ليله المحطه",
  "1621": "ليله جميله يا محلاها",
  "1622": "ليلي مراد  اغنية أبجد هوز حطي كلمن",
  "1623": "ليلي مراد و نجيب الريحاني‫  اغنية عيني بترف",
  "1624": "ليه ازعل",
  "1625":
    "ليه تشغل بالك عبد الحليم حافظ   Leih Teshghel Balak - Abdel Halim Hafez",
  "1626": "ليه يا سي احمد",
  "1627": "ما أشربش الشاى",
  "1628": "ما باعرف",
  "1629": "ما بيسالش عليه",
  "1630": "ما تغلوش علينا",
  "1631": "ما تقولش بكره",
  "1632": "ما دام بعادي",
  "1633": "ما شربش الشاي",
  "1634": "ما قدرش احب اتنين شادية",
  "1635": "ما يكونش دا الي اسمه الهوى",
  "1636": "ماخدش العجوز انا",
  "1637": "ماشي الطريق عبد الحليم حافظ   Mashy El Tareeq - Abdel Halim Hafez",
  "1638": "مالك ومالي عبد الحليم حافظ   Malak We Maly - Abdel Halim Hafez",
  "1639": "ماليش أمل في الدنيا دي",
  "1640": "ماما يا حلوه",
  "1641": "مبروك عليك",
  "1642": "مبروك عليكي",
  "1643": "متصدقنيش عبد الحليم حافظ   Ma Tesadaneesh - Abdel Halim Hafez",
  "1644": "متقولش انا اسف",
  "1645": "مجنون ليلى - اسمهان و محمد عبد الوهاب",
  "1646": "محبوبة قلبي هالة نصري شمس الدين MAHER",
  "1647": "محبوبه قلبى هلا",
  "1648": "محلاهاعيشة الفلاّح - اسمهان",
  "1649": "محمد عبد الوهاب  اغنية ليه يا عين ليلي طال",
  "1650": "مداح القمر عبد الحليم حافظ   Madah El Amar - Abd El Halim Hafez",
  "1651": "مركب الأشواق عبد الحليم حافظ   Markeb Al Oshaa - Abdel Halim Hafez",
  "1652": "مش بإيدي العشق",
  "1653": "مش قلتلك",
  "1654": "مش ممكن",
  "1655": "مش ممكن اقدر اخاصمك",
  "1656": "مشغول عبد الحليم حافظ   Mashghool Wehyatek - Abdel Halim Hafez",
  "1657": "معادنا بكره",
  "1658": "معقولة حلاوتك دي (حفلة)",
  "1659": "معلش النوبه دي",
  "1660": "مغرور عبد الحليم حافظ   Maghror - Abd El Halim Hafez",
  "1661": "مكانش وقته",
  "1662": "مكسوفه منك",
  "1663": "ملا الكاسات",
  "1664":
    "من الجهرة للسالمية عبد الحليم حافظ   Min Aljuhara lilssalimia - Abdel Halim Hafez",
  "1665": "من بعد",
  "1666": "من بعيد يا حبيبى اسلم",
  "1667":
    "من تكون حبيبتي عبد الحليم حافظ   Habebaty Man Takon - Abdel Halim Hafez",
  "1668": "من غير عتاب",
  "1669": "منايا فى قربك",
  "1670": "منتزاعل و منرضى",
  "1671": "منقول خلصنا",
  "1672": "مني عيني",
  "1673": "موال أول ماشفتكيا ليله بيضا",
  "1674": "موال بتزكر يا قلبى",
  "1675": "موال جمال محمله - اسمهان",
  "1676": "موال غدار يا زمان",
  "1677": "موال كنت انتهيت",
  "1678": "موال لا تشتكي - نصري شمس الدين",
  "1679": "موعود عبد الحليم حافظ   Mawood - Abd El Halim Hafez",
  "1680": "ميمون",
  "1681": "مين اللى يعطف على حالى",
  "1682": "مين قالك",
  "1683": "مين قاللاك تسكن",
  "1684": "مين يرحم المظلوم من قسوة الظالم",
  "1685": "نارى و جنتى",
  "1686": "نازك - (قصيدة) حبيب الروح",
  "1687": "نازك - (قصيدة) رسالتي إليك يا حبيبي",
  "1688": "نازك - أنا الربيع يا جميلة 1958",
  "1689": "نازك - الجمال - تسجيل إذاعي 1958",
  "1690": "نازك - الكلام اللي أنا قلته (الحفل الأول) - قصر النيل 1963",
  "1691": "نازك - الكلام اللي أنا قلته",
  "1692": "نازك - أحببته طيفا بأحلامي عبر",
  "1693": "نازك - أنا والنجوم صاحيين - تسجيل إذاعي",
  "1694": "نازك - أنا والنجوم صاحيين - حفل الباخرة سودان في الخمسينات",
  "1695": "نازك - بلبل طواه أيام  ويا الزمان بيميل",
  "1696": "نازك - جمال الروح",
  "1697": "نازك - حبيبي لا تسل قلبي",
  "1698": "نازك - فاكرك وفاكرني",
  "1699": "نازك - ليلة شعت لنا بالنور إذ هلّ بهاها",
  "1700": "نازك - ليه يا عينيا",
  "1701": "نازك - ماليش في الدنيا غير قلبي",
  "1702": "نازك - مش حاقولك",
  "1703": "نازك - مفاتن المساء  ليت للبرّاق عينا - حفل معهد الموسيقى 1954",
  "1704": "نازك - نداء العطر",
  "1705": "نازك - وصلة ليالي الأنس - حفل الباخرة سودان مايو 1954",
  "1706": "نازك - يا جنة العشاق  كل  دقة في قلبي - وصلة حفل 1959",
  "1707": "نازك - يا من بنور الحق يهدينا",
  "1708": "نازك - يا نجمة جنب القمر",
  "1709": "ناطر انا ناطر",
  "1710": "ناظم الغزالي  مروا علي الحلوين  (النسخة الاصلية)",
  "1711": "ناظم الغزالي - احلى الاغاني (استوديو )",
  "1712": "ناظم الغزالي - العروسة العربية (النسخة الاصلية)",
  "1713": "ناظم الغزالي - حلو و بوجنتك شامة (النسخة الأصلية)",
  "1714": "ناظم الغزالي - دعني من مواعيدك (النسخة الاصلية)",
  "1715": "ناظم الغزالي - قول واتمنى عليه (النسخة الاصلية)",
  "1716": "ناظم الغزالي - يا أم العيون السود (النسخة الاصلية)",
  "1717": "ناظم الغزالي - يا من لعبت (النسخة الاصلية)",
  "1718": "ناظم الغزالي -هلا هلا (النسخة الاصلية)",
  "1719": "ناظم الغزالي حفلة الكويت - اقول وقد ناحت (النسخة الأصلية)",
  "1720":
    "نام يا حبيبي نام عبد الحليم حافظ   Naam ya Habeeby Naam - Abdel Halim Hafez",
  "1721": "نبتدي منين الحكاية عبد الحليم حافظ   Mawood - Abd El Halim Hafez",
  "1722": "نجيب السراج  غدٍ ألقاك  najib alsrraj",
  "1723": "نجيب السراج - بالكحلة سحرتيني يا غصين البان",
  "1724": "نجيب السراج - بربك عودي ♪",
  "1725": "نجيب السراج - فوق النخل يا سليمى",
  "1726": "نجيب السراج - ليش الزعل يا خالا",
  "1727": "نجيب السراج - هل المسك منها - najip elsaraj",
  "1728": "نجيب السراج - يا حلوة ميلي (Najib al-Sarraj - Ya Helwah Mili)",
  "1729":
    "نجيب السراج - يا ساحري ما اجملك (Najib al-Sarraj - Ya Saheri Ma Ajmalak)",
  "1730": "نجيب السراج أحب ليالي الشتاء",
  "1731": "نجيب السراج عسلي عسلي عسلية",
  "1732": "نجيب السراج عيون العسلية وسود عيونك سود",
  "1733": "نصري شمس الدين - يا ليلى احكيلي Nasri Shamseddine",
  "1734": "نصري شمس الدين -ناطر",
  "1735": "نصري شمس الدين -يا مارق عالطواحين",
  "1736": "نصري شمس الدين -ياحلوه الى عالجسر",
  "1737": "نعمت مساء - نجيب السراج",
  "1738": "نعمل ايه",
  "1739": "نعيما يا حبيبى",
  "1740": "نقله نقله",
  "1741": "نهايه الحكايه",
  "1742": "نويت اداري آلامي - اسمهان",
  "1743": "هدونى هدونى",
  "1744": "هل تيم البان - اسمهان",
  "1745": "هلا يا ليلى",
  "1746": "هي دي هيا عبد الحليم حافظ   Heya De Heya - Abdel Halim Hafez",
  "1747": "و الله غلابه",
  "1748": "و النبي حلوين",
  "1749": "و النبي وحشتونا",
  "1750": "و حياه ابنك",
  "1751": "و دي فيها ايه",
  "1752": "و دي فيها حاجه",
  "1753": "واحد + واحد",
  "1754": "وجه القمر",
  "1755": "وحدي",
  "1756": "وحشتني",
  "1757": "وحياة عينيك شادية",
  "1758": "وحياة قلبي وافراحة عبد الحليم حافظ  Wehyat Alby - Abdel Halim Hafez",
  "1759": "وحياتك انت",
  "1760": "ودع هواك",
  "1761": "ودينى مطرح ما تودينى",
  "1762": "وعد و مكتوب",
  "1763":
    "يا أهلا بالمعارك عبد الحليم حافظ   Ya Ahlan Belmaarek - Abdel Halim Hafez",
  "1764": "يا اعز من عينى",
  "1765": "يا اولاد حارتنا",
  "1766": "يا بدر نورك سبانى",
  "1767": "يا بدع الورد - اسمهان",
  "1768": "يا بلادنا عبد الحليم حافظ   Allah Ya Beladna - Abdel Halim Hafez",
  "1769":
    "يا بلادي لا تنامي عبد الحليم حافظ   Ya Baladna La Tanamy - Abdel Halim Hafez",
  "1770": "يا بنت الناس",
  "1771": "يا بنت خالي",
  "1772": "يا بهية وخبرينى",
  "1773":
    "يا جمال يا حبيب الملايين عبد الحليم حافظ   Ya Gamal Ya Habib El Malayeen - Abdel Halim Hafez",
  "1774": "يا حارمني حنانك",
  "1775": "يا حاسدين الناس",
  "1776": "يا حبيب الروح",
  "1777": "يا حبيبى ارجع لى",
  "1778": "يا حبيبى خد عينية",
  "1779": "يا حبيبي تعال الحقني - اسمهان",
  "1780": "يا حبيبي عود لي تاني",
  "1781": "يا حسن يا خولي الجنينه",
  "1782": "يا حلوه عالجسر",
  "1783": "يا حنه يا حنه",
  "1784": "يا خاين",
  "1785": "يا خلي القلب عبد الحليم حافظ   Ya Khaley El Alb - Abdel Halim Hafez",
  "1786": "يا دبلة الخطوبه",
  "1787": "يا دنيا زوقوكي",
  "1788": "يا راجل يا عجوز",
  "1789": "يا رايحين للنبي",
  "1790": "يا رب يا عالم الحال",
  "1791": "يا ربيعي عبد الحليم حافظ   Ya Rabeeaaey- Abdel Halim Hafez",
  "1792": "يا روحي انا",
  "1793": "يا سارق من عينى النوم",
  "1794": "يا سلوى فين انتى تعالى",
  "1795": "يا سناره",
  "1796": "يا سي احمد",
  "1797": "يا شاغلني و قلبك خالي شادية",
  "1798": "يا طيور - اسمهان",
  "1799": "يا عشّاق النبي",
  "1800": "يا فجر مالك حزين",
  "1801": "يا قلبى أصبر ع الأيام",
  "1802": "يا قلبى مالك ليه فرحان",
  "1803": "يا قلبي خبي عبد الحليم حافظ  Ya Alby Khabby - Abdel Halim Hafez",
  "1804": "يا قلبي سيبك",
  "1805": "يا للى غيابك حيرنى",
  "1806": "يا ليالي البشر - اسمهان",
  "1807": "يا ليل دق الهوي بابي",
  "1808": "يا ليل سكونك حنان",
  "1809": "يا مسافر بورسعيد",
  "1810": "يا مسافر وحدك - نجاة  Ya Mesafer Wahdak - Nagat",
  "1811": "يا ملاك الحب",
  "1812": "يا نايمة بين الشموع",
  "1813": "يا نايمه الليل",
  "1814": "يا نبيا سمت بك العلياء و ياست نظره",
  "1815": "يا نجف",
  "1816": "يا نور عيني",
  "1817": "يا نور عينيي",
  "1818": "يا هاجر باحبك",
  "1819": "يا هلترى يا زمان هرجع لاوطانى",
  "1820": "يا ولاد حارتنا",
  "1821": "يابيضة ياحلوة - نجيب السراج",
  "1822": "ياجميله يا زينه حتتنا",
  "1823": "ياختى عليه",
  "1824": "ياديرتي مالك علينا لوم - اسمهان",
  "1825": "يالعينيك ويالي  (حديث العيون ) - اسمهان",
  "1826": "ياللى انت ناسينى",
  "1827": "ياللى ملكتى الفؤاد",
  "1828": "ياللي انت قلبك",
  "1829": "ياللي بحبك بنيت الأمـاني - اسمهان",
  "1830": "يام الاساور",
  "1831": "يانار فؤادي - اسمهان",
  "1832": "يسعد صباحك يا بدر ــ نجيب السراج",
  "1833": "يكفى بكا يا دموع العين",
  "1834": "يلا بنا يلا",
  "1835": "يلا يلا",
  "1836": "يللي هواك شاغل بالي - اسمهان",
  "1837": "يوم السفر"
};
